/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Trainer;

import Business.Child.ChildDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BackgroundCheckOrganisation;
import Business.Organization.Organization;
import Business.Parent.Parent;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BackgroundCheckWorkRequest;
import Business.WorkQueue.ParentWorkRequest;
import Business.WorkQueue.TrainingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.BackgroundCheckManager.BackgroundCheckScheduleAppointment;

/**
 *
 * @author jaspr
 */
public class TrainerWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrainerWorkRequestJPanel
     */
    EcoSystem business;
    JPanel userProcessContainer;
    Enterprise enterprise;
    Organization organization;
    ChildDirectory childdir;
    JPanel rightpanel1;
    ParentWorkRequest parentrequest;
    UserAccount account;
    TrainingWorkRequest trainingWorkRequest;
    public TrainerWorkRequestJPanel(EcoSystem business, JPanel userProcessContainer,
            Enterprise enterprise,Organization organization,
            JPanel rightpanel1,UserAccount account) {
        initComponents();
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.rightpanel1 = rightpanel1;
        this.account = account;
        
        btn_assign.setVisible(false);
        panel_assign.setVisible(false);
        panel_trainingcompleted.setVisible(false);
        btn_trainingcompleted.setVisible(false);
        
        //JOptionPane.showMessageDialog(rightpanel1, account);
        
        populateTable();
    }
    
     public void checkStatus(int selectedRow){
        DefaultTableModel model = (DefaultTableModel) tbl_trainer.getModel();
        Object statusval = tbl_trainer.getValueAt(selectedRow, 4);
        
        if(statusval.equals("Requested For Training")){
            btn_assign.setVisible(true);
            panel_assign.setVisible(true);
            panel_trainingcompleted.setVisible(false);
            btn_trainingcompleted.setVisible(false);
        }
        else if(statusval.equals("Training in Progress")){
            btn_assign.setVisible(false);
            panel_assign.setVisible(false);
            panel_trainingcompleted.setVisible(true);
            btn_trainingcompleted.setVisible(true);
        }
        else if(statusval.equals("Training Completed")){
            btn_assign.setVisible(false);
            panel_assign.setVisible(false);
            panel_trainingcompleted.setVisible(false);
            btn_trainingcompleted.setVisible(false);
        }
        
        
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_trainer.getModel();
        model.setRowCount(0);
        //JOptionPane.showMessageDialog(rightpanel1, organization);
        //JOptionPane.showMessageDialog(rightpanel1, organization.getWorkQueue().getWorkRequestList());
        for(WorkRequest workrequest:organization.getWorkQueue().getWorkRequestList()){
            if(workrequest instanceof TrainingWorkRequest){
                Object[] row = new Object[6];
                   //JOptionPane.showMessageDialog(panel_request, workrequest.getStatus());
                   row[0] = workrequest.getSender().getRole();
                   row[1] =  workrequest;
                   row[2] = ((TrainingWorkRequest) workrequest).getSender();
                   row[3] = workrequest.getReceiver() == null ? null : account;
                   row[4] = workrequest.getStatus();
                    
                   row[5] = ((TrainingWorkRequest) workrequest).getParent();
                   //row[6] = ((BackgroundCheckWorkRequest) workrequest).getParent().getParentid();
                   model.addRow(row);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_trainer = new javax.swing.JTable();
        panel_trainingcompleted = new javax.swing.JPanel();
        btn_trainingcompleted = new javax.swing.JButton();
        panel_assign = new javax.swing.JPanel();
        btn_assign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(204, 255, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 153, 0));

        tbl_trainer.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tbl_trainer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sender Role", "Message", "Sender Name", "Reciever Name", "Status", "Parent to Train"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_trainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_trainerMouseClicked(evt);
            }
        });
        tbl_trainer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_trainerPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_trainer);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 940, 250));

        btn_trainingcompleted.setBackground(new java.awt.Color(51, 51, 51));
        btn_trainingcompleted.setForeground(new java.awt.Color(255, 255, 255));
        btn_trainingcompleted.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png"))); // NOI18N
        btn_trainingcompleted.setText("Training Completed");
        btn_trainingcompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trainingcompletedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_trainingcompletedLayout = new javax.swing.GroupLayout(panel_trainingcompleted);
        panel_trainingcompleted.setLayout(panel_trainingcompletedLayout);
        panel_trainingcompletedLayout.setHorizontalGroup(
            panel_trainingcompletedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trainingcompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_trainingcompletedLayout.setVerticalGroup(
            panel_trainingcompletedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_trainingcompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.add(panel_trainingcompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 190, 40));

        btn_assign.setBackground(new java.awt.Color(51, 51, 51));
        btn_assign.setForeground(new java.awt.Color(255, 255, 255));
        btn_assign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/assign.png"))); // NOI18N
        btn_assign.setText("Assign To Me");
        btn_assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_assignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_assignLayout = new javax.swing.GroupLayout(panel_assign);
        panel_assign.setLayout(panel_assignLayout);
        panel_assignLayout.setHorizontalGroup(
            panel_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_assignLayout.createSequentialGroup()
                .addComponent(btn_assign, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_assignLayout.setVerticalGroup(
            panel_assignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_assign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.add(panel_assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 170, 40));

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/training.jpg"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 800, 520));

        jLabel2.setBackground(new java.awt.Color(153, 153, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("MANAGE REQUESTS FOR TRAINING");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1273, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_trainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_trainerMouseClicked
        // TODO add your handling code here:
        
        tbl_trainer.addMouseListener(new MouseAdapter() {
           
            public void mousePressed(MouseEvent e) {
              int selectedRow = tbl_trainer.getSelectedRow();
              checkStatus(selectedRow);
            }
           
       });
       
    }//GEN-LAST:event_tbl_trainerMouseClicked

    private void tbl_trainerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_trainerPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_trainerPropertyChange

    private void btn_trainingcompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trainingcompletedActionPerformed
        // TODO add your handling code here:
        
       DefaultTableModel model = (DefaultTableModel) tbl_trainer.getModel();
        int selectedRow = tbl_trainer.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a work request");
            return;
        }
        else{
        Parent parentval = (Parent)(UserAccount)tbl_trainer.getValueAt(selectedRow, 5);
        UserAccount bckgrounval = (UserAccount)tbl_trainer.getValueAt(selectedRow, 2);
        
        WorkRequest workrequest = (WorkRequest) tbl_trainer.getValueAt(selectedRow, 1);
        workrequest.setStatus("Training Completed");
        workrequest.setSender(account);
        workrequest.setMessage("Training Completed");
        
        JOptionPane.showMessageDialog(rightpanel1, "Training Completed");
        populateTable();
       
        checkStatus(selectedRow);
        
        for(WorkRequest wr:bckgrounval.getWorkQueue().getWorkRequestList()){
            wr.setSender(account);
            wr.setMessage("Training Completed");
            wr.setMessage("Training Completed");
            wr.setStatus("Training Completed");
         }
        for(WorkRequest wr:parentval.getWorkQueue().getWorkRequestList()){
            wr.setSender(account);
            wr.setMessage("Training Completed");
            wr.setMessage("Training Completed");
            wr.setStatus("Training Completed");
         }
        }
    }//GEN-LAST:event_btn_trainingcompletedActionPerformed

   
    
    
    private void btn_assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_assignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_trainer.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a work request");
            return;
        }

        Object receiverval = tbl_trainer.getValueAt(selectedRow, 3);
        Object statusval = tbl_trainer.getValueAt(selectedRow, 4);

        if ("Requested For Training".equals(statusval) || receiverval == null) {
            WorkRequest re = (WorkRequest) tbl_trainer.getValueAt(selectedRow, 1);
            re.setReceiver(account);
            re.setStatus("Training in Progress");
            re.setMessage("Training in Progress");
            re.setSender(account);
            populateTable();
            JOptionPane.showMessageDialog(null, "Work request has been assigned to you");
            checkStatus(selectedRow);
            

        }
        else{
            //JOptionPane.showMessageDialog(rightpanel1, receiverval);
            //JOptionPane.showMessageDialog(rightpanel1, account.getUsername());
            if (receiverval.equals(account)) {
                JOptionPane.showMessageDialog(null, "Work request is already assigned to you");
            }
            else if (!receiverval.equals(account.getUsername())) {
                JOptionPane.showMessageDialog(null, "Work request is assigned to someone else");
                btn_trainingcompleted.setVisible(false);
            }
        }

    }//GEN-LAST:event_btn_assignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_assign;
    private javax.swing.JButton btn_trainingcompleted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panel_assign;
    private javax.swing.JPanel panel_trainingcompleted;
    private javax.swing.JTable tbl_trainer;
    // End of variables declaration//GEN-END:variables
}
