/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterAdmin;

import Business.Child.Child;
import Business.Child.ChildDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Agency;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.ChildRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jaspr
 */
public class RegisterChildJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterChildJPanel
     */
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    JPanel userProcessContainer;
    EcoSystem business;
    Enterprise enterprise;
    Organization organization;
    ChildDirectory childdir;
    UserAccountDirectory useraccountdir;
    private static JFileChooser fileChooser = new JFileChooser();;
    ImageIcon logoImage;
    public static int count = 0;
    Child child;
        
    public RegisterChildJPanel(EcoSystem business,JPanel userProcessContainer,
            Enterprise enterprise,Organization organization, ChildDirectory childdir) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.enterprise = enterprise;
        this.organization = organization;
        
        
        this.childdir = organization.getChildDirectory();
        useraccountdir = business.getUserAccountDirectory();
       
        txt_agency.setText(organization.getName());
        lbl_txt.setVisible(false);
 
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        panel_singleparent = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        combo_gender = new javax.swing.JComboBox<>();
        txt_firstname = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        combo_race = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        combo_age = new javax.swing.JComboBox<>();
        jLabel52 = new javax.swing.JLabel();
        combo_religion = new javax.swing.JComboBox<>();
        jLabel56 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        check_specialchild = new javax.swing.JCheckBox();
        jLabel39 = new javax.swing.JLabel();
        txt_agency = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        pwdField = new javax.swing.JPasswordField();
        jLabel48 = new javax.swing.JLabel();
        btn_createaccout1 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        txt_about = new javax.swing.JTextField();
        lbl_txt = new javax.swing.JLabel();
        btn_upload = new javax.swing.JButton();
        panel_extra = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("PERSONAL INFORMATION");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 242, -1));

        panel_singleparent.setBackground(new java.awt.Color(204, 255, 153));
        panel_singleparent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setText("Gender");
        panel_singleparent.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setText("Last Name");
        panel_singleparent.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Female", "Male" }));
        combo_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_genderActionPerformed(evt);
            }
        });
        panel_singleparent.add(combo_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));
        panel_singleparent.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setText("Race");
        panel_singleparent.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        combo_race.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Race", "Black", "Asian", "White", "Pacific Islander", "unknown" }));
        panel_singleparent.add(combo_race, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 130, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("City");
        panel_singleparent.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        combo_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Age", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", " " }));
        panel_singleparent.add(combo_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 130, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setText("Special Child");
        panel_singleparent.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, 20));

        combo_religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Religion", "Hinduism", "Buddhism", "Catholism", "Christian", "Jewish", "unknown" }));
        panel_singleparent.add(combo_religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, 20));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setText("First Name");
        panel_singleparent.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Age");
        panel_singleparent.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        panel_singleparent.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, -1));
        panel_singleparent.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setText("Religion");
        panel_singleparent.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        panel_singleparent.add(check_specialchild, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 20, 20));

        jPanel2.add(panel_singleparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 440));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Agency");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_agency.setForeground(new java.awt.Color(255, 255, 255));
        txt_agency.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_agency.setEnabled(false);
        jPanel2.add(txt_agency, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 130, -1));

        jPanel5.setBackground(new java.awt.Color(204, 255, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setBorder(javax.swing.BorderFactory.createTitledBorder("USERNAME"));
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });
        jPanel5.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 250, -1));

        pwdField.setBorder(javax.swing.BorderFactory.createTitledBorder("PASSWORD"));
        pwdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdFieldKeyTyped(evt);
            }
        });
        jPanel5.add(pwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 250, -1));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel48.setText("CREATE ACCOUNT");
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        btn_createaccout1.setBackground(new java.awt.Color(51, 51, 51));
        btn_createaccout1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_createaccout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btn_createaccout1.setText("Create Account");
        btn_createaccout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createaccout1ActionPerformed(evt);
            }
        });
        jPanel5.add(btn_createaccout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 170, 40));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setText("ABOUT THE CHILD");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
        jPanel5.add(txt_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 210, 70));

        lbl_txt.setText("jLabel1");
        jPanel5.add(lbl_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, 20));

        btn_upload.setBackground(new java.awt.Color(51, 51, 51));
        btn_upload.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/upload.png"))); // NOI18N
        btn_upload.setText("UPLOAD PHOTO");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });
        jPanel5.add(btn_upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, 30));

        panel_extra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/childcare.jpg"))); // NOI18N

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panel_extra, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_extra)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pwdFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdFieldKeyTyped
        // TODO add your handling code here:
        
        

        
    }//GEN-LAST:event_pwdFieldKeyTyped

    private void pwdFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFieldKeyReleased

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void combo_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_genderActionPerformed
    private String browseImageFile() {
        JFileChooser chooseFile = new JFileChooser();
        chooseFile.showOpenDialog(null);
        try {
            File file = chooseFile.getSelectedFile();
            String filePath = file.getPath();
            System.out.println(filePath);
            lbl_txt.setText(filePath);
            return filePath;
        } catch (Exception e) {
            return "";
        }
         
    }
    private void btn_createaccout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createaccout1ActionPerformed
        // TODO add your handling code here:
         if(txt_firstname.getText().isEmpty() || txt_lastname.getText().isEmpty()
            || txt_city.getText().isEmpty() || txt_agency.getText().isEmpty()
            || txtUserName.getText().isEmpty() || pwdField.getText().isEmpty()
                  || txt_about.getText() == null){
            
            JOptionPane.showMessageDialog(panel_singleparent, "Please Provide All Details");
            
        }
         else if(lbl_txt.getText().isEmpty()){
             JOptionPane.showMessageDialog(fileChooser, "Please Upload Photo of Child");
         }
        else if(combo_age.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(combo_age, "Please Selct child Age");
        }
        
        else if(combo_gender.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(combo_age, "Please Selct child Gender");
        }
        else if(combo_race.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(combo_age, "Please Selct child Race");
        }
        else if(combo_religion.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(combo_age, "Please Select child Religion");
        }
        
        else{
 
            String firstname = txt_firstname.getText();
            String lastname = txt_lastname.getText();
            String gender = String.valueOf(combo_gender.getSelectedItem());
            int age =Integer.parseInt((String) combo_age.getSelectedItem());
            String city = txt_city.getText();
            String race = String.valueOf(combo_race.getSelectedItem());
            String religion = String.valueOf(combo_religion.getSelectedItem());
            String about = txt_about.getText();
            
            String username = txtUserName.getText();
            String password = pwdField.getText();
            SimpleDateFormat formatter= new SimpleDateFormat("yyyy-MM-dd");
            Date date_profile = new Date(System.currentTimeMillis());
            String image = lbl_txt.getText();
            boolean check_specialChild;
            
            if(check_specialchild.isSelected()){
                check_specialChild = true;
            }
            else{
                check_specialChild = false;
            }

            txt_agency.setText(organization.getName());
            
            
                if(useraccountdir.checkIfUsernameIsUnique(username)){
                    child = childdir.addChild(++count,firstname,lastname,gender,age,city,race,religion,about,date_profile,
                                                            username,password,organization,check_specialChild, image);
                    business.getChildDirectory().addChild(age, firstname, lastname, gender, age, city, race, religion, about, date_profile, username, password, organization, check_specialChild, image);
                    useraccountdir.createUserAccount(username, password, new ChildRole());
      
                    JOptionPane.showMessageDialog(combo_age, "Child Added");
                    
                    //JOptionPane.showMessageDialog(combo_age, childdir.getChildlist());
                    
                }
                else{
                    JOptionPane.showMessageDialog(combo_age, "Username Already Exist");
                }
                
            
           
        }
        
    }//GEN-LAST:event_btn_createaccout1ActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        browseImageFile();
    }//GEN-LAST:event_btn_uploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createaccout1;
    private javax.swing.JButton btn_upload;
    private javax.swing.JCheckBox check_specialchild;
    private javax.swing.JComboBox<String> combo_age;
    private javax.swing.JComboBox<String> combo_gender;
    private javax.swing.JComboBox<String> combo_race;
    private javax.swing.JComboBox<String> combo_religion;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_txt;
    private javax.swing.JLabel panel_extra;
    private javax.swing.JPanel panel_singleparent;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txt_about;
    private javax.swing.JTextField txt_agency;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    // End of variables declaration//GEN-END:variables
}
