/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FosterAdmin;

import Business.Child.Child;
import Business.Child.ChildDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.Parent.ViewChildrenJPanel;

/**
 *
 * @author jaspr
 */
public class SeeChildDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SeeChildDetailsJPanel
     */
    EcoSystem business;
    Child child;
    ListOfChildrenJPanel listofchildrenjpanel;
    JPanel userProcessContainer;
    JPanel rightpanel1;
    //private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    //private final JFileChooser fileChooser = new JFileChooser();
    //Date date;
    //ImageIcon logoImage;
    public SeeChildDetailsJPanel(JPanel userProcessContainer,EcoSystem business, 
            Child child,JPanel rightpanel) {
        initComponents();
        this.business = business;
        this.child = child;
        this.userProcessContainer = userProcessContainer;
        rightpanel1 = rightpanel;

        txt_about.setText(child.getAbout_child());
        
        txt_firstname.setText(child.getFirstname());
        txt_religion.setText(child.getLastname());
        txt_city.setText(child.getCity());
        txt_age.setText(String.valueOf(child.getAge()));
        txt_gender.setText(String.valueOf(child.getGender()));
        txt_race.setText(child.getRace());
        txt_religion.setText(child.getReligion());
        txt_lastname.setText(child.getLastname());
        
        txt_about.setEnabled(false);
        
        txt_firstname.setEnabled(false);
        txt_religion.setEnabled(false);
        txt_city.setEnabled(false);
        txt_age.setEnabled(false);
        txt_gender.setEnabled(false);
        txt_race.setEnabled(false);
        txt_religion.setEnabled(false);
        txt_lastname.setEnabled(false);
        
        displayImage();
        
        combo_age.setEnabled(false);
        combo_gender.setEnabled(false);
        combo_race.setEnabled(false);
        combo_religion.setEnabled(false);
        txt_lastrofileupdated.setText(String.valueOf(child.getLast_profileupdated()));

    }
    public void displayImage() {
        BufferedImage image = null;
        String filename = child.getImage();
        try {
            image = ImageIO.read(new File(filename));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File not found");
        }
        ImageIcon icon = new ImageIcon(image);
        imageLable.setIcon(icon);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        panel_singleparent = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_religion = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        txt_city = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_gender = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_race = new javax.swing.JTextField();
        combo_gender = new javax.swing.JComboBox<>();
        combo_age = new javax.swing.JComboBox<>();
        combo_race = new javax.swing.JComboBox<>();
        combo_religion = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_seeDetails1 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        txt_lastrofileupdated = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        txt_about = new javax.swing.JTextField();
        btn_seeDetails2 = new javax.swing.JButton();
        imageLable = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 0));
        jLabel28.setText("PERSONAL INFORMATION");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, -1));

        panel_singleparent.setBackground(new java.awt.Color(204, 255, 153));
        panel_singleparent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setText("Gender");
        panel_singleparent.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setText("Last Name");
        panel_singleparent.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 10));
        panel_singleparent.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setText("Race");
        panel_singleparent.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("City");
        panel_singleparent.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Age");
        panel_singleparent.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        panel_singleparent.add(txt_religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 70, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setText("Religion");
        panel_singleparent.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        panel_singleparent.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 130, -1));
        panel_singleparent.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, -1));
        panel_singleparent.add(txt_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 60, -1));
        panel_singleparent.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 60, -1));
        panel_singleparent.add(txt_race, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 70, -1));

        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Female", "Male" }));
        combo_gender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_genderItemStateChanged(evt);
            }
        });
        combo_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_genderActionPerformed(evt);
            }
        });
        panel_singleparent.add(combo_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 100, -1));

        combo_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Age", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));
        combo_age.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_ageItemStateChanged(evt);
            }
        });
        combo_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_ageActionPerformed(evt);
            }
        });
        panel_singleparent.add(combo_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 100, -1));

        combo_race.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Black", "Asian", "White", "Pacific Islander", "unknown" }));
        combo_race.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_raceItemStateChanged(evt);
            }
        });
        combo_race.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_raceActionPerformed(evt);
            }
        });
        panel_singleparent.add(combo_race, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 100, -1));

        combo_religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Hinduism", "Buddhism", "Catholism", "Christian", "Jewish", "unknown" }));
        combo_religion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_religionItemStateChanged(evt);
            }
        });
        combo_religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_religionActionPerformed(evt);
            }
        });
        panel_singleparent.add(combo_religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 100, 20));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel58.setText("First Name");
        panel_singleparent.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jPanel2.add(panel_singleparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, 480));

        jPanel5.setBackground(new java.awt.Color(204, 255, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_seeDetails1.setBackground(new java.awt.Color(51, 51, 51));
        btn_seeDetails1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_seeDetails1.setForeground(new java.awt.Color(255, 255, 255));
        btn_seeDetails1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        btn_seeDetails1.setText("Update Details");
        btn_seeDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seeDetails1ActionPerformed(evt);
            }
        });
        jPanel5.add(btn_seeDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 180, 40));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(153, 153, 0));
        jLabel55.setText("Last Detials Updated");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        txt_lastrofileupdated.setEnabled(false);
        jPanel5.add(txt_lastrofileupdated, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 260, -1));

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(153, 153, 0));
        jLabel57.setText("ABOUT THE CHILD");
        jPanel7.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txt_about.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.add(txt_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 100));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 190, 156));

        btn_seeDetails2.setBackground(new java.awt.Color(51, 51, 51));
        btn_seeDetails2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_seeDetails2.setForeground(new java.awt.Color(255, 255, 255));
        btn_seeDetails2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_seeDetails2.setText("Save updation");
        btn_seeDetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seeDetails2ActionPerformed(evt);
            }
        });
        jPanel5.add(btn_seeDetails2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 180, 40));

        imageLable.setText("jLabel1");
        jPanel5.add(imageLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 170, 190));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/childcare.jpg"))); // NOI18N
        jPanel6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 540));

        back.setBackground(new java.awt.Color(153, 153, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(51, 51, 51));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackIcon.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seeDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seeDetails1ActionPerformed
        // TODO add your handling code here:

        //btn_requestmedical.setEnabled(true);
        combo_age.setEnabled(true);
        combo_gender.setEnabled(true);
        combo_race.setEnabled(true);
        combo_religion.setEnabled(true);
        txt_about.setEnabled(true);

        txt_firstname.setEnabled(true);
        txt_religion.setEnabled(true);
        txt_city.setEnabled(true);
        txt_age.setEnabled(true);
        txt_gender.setEnabled(true);
        txt_race.setEnabled(true);
        txt_religion.setEnabled(true);
        txt_lastname.setEnabled(true);
        //btn_update.setEnabled(true);
    }//GEN-LAST:event_btn_seeDetails1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(fileChooser, userProcessContainer);
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backActionPerformed

    private void combo_religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_religionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_religionActionPerformed

    private void combo_religionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_religionItemStateChanged
        // TODO add your handling code here:
        txt_religion.setText(String.valueOf(combo_religion.getSelectedItem()));
    }//GEN-LAST:event_combo_religionItemStateChanged

    private void combo_raceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_raceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_raceActionPerformed

    private void combo_raceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_raceItemStateChanged
        // TODO add your handling code here:
        txt_race.setText(String.valueOf(combo_race.getSelectedItem()));
    }//GEN-LAST:event_combo_raceItemStateChanged

    private void combo_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_ageActionPerformed

    private void combo_ageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_ageItemStateChanged
        // TODO add your handling code here:
        txt_age.setText(String.valueOf(combo_age.getSelectedItem()));
    }//GEN-LAST:event_combo_ageItemStateChanged

    private void combo_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_genderActionPerformed
        // TODO add your handling code here:
        txt_gender.setText(String.valueOf(combo_gender.getSelectedItem()));
    }//GEN-LAST:event_combo_genderActionPerformed

    private void combo_genderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_genderItemStateChanged
        // TODO add your handling code here:
        txt_gender.setText(String.valueOf(combo_gender.getSelectedItem()));
    }//GEN-LAST:event_combo_genderItemStateChanged

    private void btn_seeDetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seeDetails2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_seeDetails2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btn_seeDetails1;
    private javax.swing.JButton btn_seeDetails2;
    private javax.swing.JComboBox<String> combo_age;
    private javax.swing.JComboBox<String> combo_gender;
    private javax.swing.JComboBox<String> combo_race;
    private javax.swing.JComboBox<String> combo_religion;
    private javax.swing.JLabel imageLable;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panel_singleparent;
    private javax.swing.JTextField txt_about;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_gender;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_lastrofileupdated;
    private javax.swing.JTextField txt_race;
    private javax.swing.JTextField txt_religion;
    // End of variables declaration//GEN-END:variables
}
