/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;

/**
 *
 * @author jaspr
 */
public class CommunityJPanel extends javax.swing.JPanel {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    /**
     * Creates new form CommunityJPanel
     */
    JPanel workarea;
    City city;
    public CommunityJPanel(JPanel workarea,City city) {
        initComponents();
        
        this.workarea = workarea;
        this.city = city;
        
        populatecombocity();
        refreshTable();
    }
    
    public void populatecombocity(){
        combo_city.removeAllItems();
        combo_city.addItem("Select City");
        for(City c:city.getCitylist()){
            combo_city.addItem(String.valueOf(c));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combo_city = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_community = new javax.swing.JTextField();
        btn_addcommunity = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_community = new javax.swing.JTable();
        btn_remove = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("City");

        combo_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_cityActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Community");

        btn_addcommunity.setText("Add Community");
        btn_addcommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcommunityActionPerformed(evt);
            }
        });

        tbl_community.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "City", "Community"
            }
        ));
        jScrollPane1.setViewportView(tbl_community);

        btn_remove.setText("Remove Community");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_community))
                            .addComponent(btn_addcommunity)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76)
                                .addComponent(combo_city, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 61, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btn_remove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_community, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btn_addcommunity)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_remove)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addcommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addcommunityActionPerformed
        // TODO add your handling code here:
        String alphabets_regex = "^[a-zA-Z]*$";
  
        int selectedcityindex = combo_city.getSelectedIndex();
        if(selectedcityindex == 0){
            JOptionPane.showMessageDialog(combo_city, "Please Select City");
            return;
        }
        else  if(txt_community.getText().equals("")){
            JOptionPane.showMessageDialog(jScrollPane1, "Please enter community");
        }
        else if(!txt_community.getText().matches(alphabets_regex)){
            JOptionPane.showMessageDialog(jScrollPane1, "Please enter correct community name");
        }
        else{
            boolean check = checkComm();
            if(check == false){
                for(City c:city.getCitylist()){
                    if(c.getName().equals(combo_city.getSelectedItem())){
                        City cityselected = c;
                        Community community = c.addcommunity();
                        community.setName(txt_community.getText());
                        city.getCommunitylist().add(community);
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(combo_city, "Community already exist");
            }
            
        }
    
        refreshTable();
        
    }//GEN-LAST:event_btn_addcommunityActionPerformed
    public boolean checkComm(){
        
        for(City c:city.getCitylist()){
            if(String.valueOf(c.getName()).equals(combo_city.getSelectedItem())){
                for(int i=0;i<c.getCommunitylist().size();i++){
                    
                    if(String.valueOf(c.getCommunitylist().get(i).getName()).
                            equals(String.valueOf(txt_community.getText()))){
                        return true;
                    }
                }
            }
        
    }
        return false;
    }

    
    private void combo_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_cityActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)tbl_community.getModel();
        int selectedrow = tbl_community.getSelectedRow();
        if(selectedrow < 0){
            JOptionPane.showMessageDialog(btn_remove, "Please select Community");
        }
        else{
            Community c = (Community)tbl_community.getValueAt(selectedrow, 1);
            City ci = (City)tbl_community.getValueAt(selectedrow, 0);

            ci.removeCommunity(c);
            JOptionPane.showMessageDialog(btn_remove, "Community Removed from City " + ci);

            refreshTable();
        }
        
        
    }//GEN-LAST:event_btn_removeActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addcommunity;
    private javax.swing.JButton btn_remove;
    private javax.swing.JComboBox<String> combo_city;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_community;
    private javax.swing.JTextField txt_community;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel)tbl_community.getModel();
        model.setRowCount(0);
        for(City c:city.getCitylist()){
            for(Community comm : c.getCommunitylist()){
            Object row[] = new Object[2];
            row[0] = c;
            row[1] = comm;
            model.addRow(row);
            }
        }

    }
}
