/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Community;
import model.House;

/**
 *
 * @author jaspr
 */
public class HouseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HouseJPanel
     */
    JPanel workarea;
    City city;
    House h;
    public HouseJPanel(JPanel workarea,City city) {
        initComponents();
        
        this.workarea = workarea;
        this.city = city;
        
        populatecombocity();
        refreshTable();
        
    }
    
    public void populatecombocity(){
        combo_city.removeAllItems();
        combo_city.addItem("Select City");
        for(City c : city.getCitylist()){
            combo_city.addItem(String.valueOf(c));
        }
    }
    
    public void refreshTable(){
        DefaultTableModel model = (DefaultTableModel)tbl_house.getModel();
        model.setRowCount(0);
        
        for(City c:city.getCitylist()){
            //if(c.getName().equals(combo_city.getSelectedItem())){
                for(Community comm:c.getCommunitylist()){
                   for(House ho:comm.getHouselist()){
                       //JOptionPane.showMessageDialog(combo_city, c + " " + comm + " "+ ho );
                      
                         Object row[] = new Object[3];
                         row[0] = c;
                         row[1] = comm;
                         row[2] = ho;
                         model.addRow(row);
                        }
                    
                }
            //}
        }
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_house = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combo_city = new javax.swing.JComboBox<>();
        combo_community = new javax.swing.JComboBox<>();
        txt_house = new javax.swing.JTextField();
        btn_addhouse = new javax.swing.JButton();
        btn_removehouse = new javax.swing.JButton();

        tbl_house.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "City", "Community", "House"
            }
        ));
        jScrollPane1.setViewportView(tbl_house);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("City");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Community");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("House");

        combo_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_cityActionPerformed(evt);
            }
        });

        combo_community.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_community.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_communityActionPerformed(evt);
            }
        });

        btn_addhouse.setText("Add House");
        btn_addhouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addhouseActionPerformed(evt);
            }
        });

        btn_removehouse.setText("Remove House");
        btn_removehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removehouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 106, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_community, 0, 163, Short.MAX_VALUE)
                            .addComponent(combo_city, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_house)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btn_addhouse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btn_removehouse)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combo_community, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_house, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_addhouse)
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_removehouse)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addhouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addhouseActionPerformed
        // TODO add your handling code here:
        
        int selectedcityindex = combo_city.getSelectedIndex();
        int selectedcommindex = combo_community.getSelectedIndex();
        String house = txt_house.getText();
         
        if(selectedcityindex == 0){
            JOptionPane.showMessageDialog(combo_city, "Please select city");
        }
        else if(selectedcityindex == 0){
            JOptionPane.showMessageDialog(combo_city, "Please select community");
        }
        else  if(txt_house.getText().equals("")){
            JOptionPane.showMessageDialog(jScrollPane1, "Please enter house");
        }
        
        else{
            boolean check = checkHouse();
            if(check == false){
                for(City c:city.getCitylist()){
                    if(c.getName().equals(combo_city.getSelectedItem())){
                        for(Community comm : city.getCommunitylist()){
                            if(comm.getName().equals(combo_community.getSelectedItem())){
                                h = comm.addHouse();
                                h.setStreetname(house);
                            }
                        }
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(combo_city, "House Already exist");
            }
        }
        
        refreshTable();

    }//GEN-LAST:event_btn_addhouseActionPerformed
    
    public boolean checkHouse(){
    
        for(City c:city.getCitylist()){
            //if(String.valueOf(c.getName()).equals(String.valueOf(combo_city.getSelectedItem()))){
                for(Community comm:c.getCommunitylist()){
                    //if(String.valueOf(comm.getName()).equals(String.valueOf(combo_community.getSelectedItem()))){
                    for(House h:comm.getHouselist()){
                        if(String.valueOf(h).equals(String.valueOf(String.valueOf(txt_house.getText())))){
                            return true;
                        }
                    }
                    //}
                }
            //}
        
        }
        return false;
    
    }
    
    private void combo_communityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_communityActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_combo_communityActionPerformed

    private void combo_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_cityActionPerformed
        // TODO add your handling code here:
        combo_community.removeAllItems();
        combo_community.addItem("Select Community");
        for(City c:city.getCitylist()){
                if(c.getName().equals(combo_city.getSelectedItem())){
                    City cityselected = c;
                    for(int i=0;i<c.getCommunitylist().size();i++){
                        combo_community.addItem(String.valueOf(c.getCommunitylist().get(i)));
                    }
                }
        }
    }//GEN-LAST:event_combo_cityActionPerformed

    private void btn_removehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removehouseActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbl_house.getModel();
        int selectedrow = tbl_house.getSelectedRow();
        if(selectedrow < 0){
            JOptionPane.showMessageDialog(btn_removehouse, "Please select Community");
        }
        else{
            Community c = (Community)tbl_house.getValueAt(selectedrow, 1);
            City ci = (City)tbl_house.getValueAt(selectedrow, 0);
            House h = (House)tbl_house.getValueAt(selectedrow, 2);
            
            c.removeHouse(h);
            JOptionPane.showMessageDialog(combo_city, "House Removed from City"+ci+" "+c);
            refreshTable();
        }
        
        
    }//GEN-LAST:event_btn_removehouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addhouse;
    private javax.swing.JButton btn_removehouse;
    private javax.swing.JComboBox<String> combo_city;
    private javax.swing.JComboBox<String> combo_community;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_house;
    private javax.swing.JTextField txt_house;
    // End of variables declaration//GEN-END:variables

   
}
