/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Pharmacist;

import Business.Child.Child;
import Business.Child.ChildDirectory;
import Business.Child.ChildLabTests;
import Business.Child.ChildPrescriptions;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Parent.ParentDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaspr
 */
public class PharmascistWorkRequestJpanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmascistWorkRequestJpanel
     */
    EcoSystem business;
    UserAccount account;
    JPanel userProcessContainer;
    Enterprise enterprise;
    Organization organization;
    ChildDirectory childdir;
    ParentDirectory parentdir;
    JPanel rightpanel1;
    public PharmascistWorkRequestJpanel(EcoSystem business, UserAccount account,
                                    JPanel userProcessContainer,Enterprise enterprise,
                                    Organization organization,
                                    ChildDirectory childdir,ParentDirectory parentdir,
                                    JPanel rightpanel1) {
        initComponents();
        this.business = business;
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.childdir = childdir;
        this.parentdir = parentdir;
        this.rightpanel1 = rightpanel1;
        
        panel_assign.setVisible(false);
        btn_assign.setVisible(false);
        panel_undermedication.setVisible(false);
        btn_undermedication.setVisible(false);
        
        lbl_txt.setText("WELCOME" + " " + account.getEmployee().getName().toUpperCase());
        populateTable();
        
    }
    
    
    
    
     public void checkStatus(int selectedRow){
        DefaultTableModel model = (DefaultTableModel) tbl_mediaction.getModel();
        Object statusval = tbl_mediaction.getValueAt(selectedRow, 4);
        
        if(statusval.equals("Request for medication")){
            panel_assign.setVisible(true);
            btn_assign.setVisible(true);
            panel_undermedication.setVisible(false);
            btn_undermedication.setVisible(false);
        }
        else if(statusval.equals("Under Medication")){
            panel_assign.setVisible(false);
            btn_assign.setVisible(false);
            panel_undermedication.setVisible(true);
            btn_undermedication.setVisible(true);
        }
        else if(statusval.equals("Medication Provided")){
            panel_assign.setVisible(false);
            btn_assign.setVisible(false);
            panel_undermedication.setVisible(true);
            btn_undermedication.setVisible(true);
        }
     }
     
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_mediaction.getModel();
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
             if (request instanceof PharmacyWorkRequest) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = request.getSender().getUsername();
                row[1] = request.getMessage();
                row[2] = request.getSender();
                row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
                //String result = ((MedicalCheckRequest) request).getTestResult();
                row[4] = request.getStatus();
                row[5] = request.getChild();
                row[6] = request;
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_mediaction = new javax.swing.JTable();
        panel_assign = new javax.swing.JPanel();
        btn_assign = new javax.swing.JButton();
        panel_undermedication = new javax.swing.JPanel();
        btn_undermedication = new javax.swing.JButton();
        lbl_txt = new javax.swing.JLabel();
        lbl_txt1 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(204, 255, 0));
        jPanel5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 153, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_mediaction.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tbl_mediaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sender UserName", "Message", "Sender Name", "Reciever Name", "Status", "Child To Check", "WorkRequest"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_mediaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mediactionMouseClicked(evt);
            }
        });
        tbl_mediaction.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_mediactionPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_mediaction);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 1060, 239));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1060, -1));

        panel_assign.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_assign.setBackground(new java.awt.Color(102, 102, 102));
        btn_assign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_assign.setForeground(new java.awt.Color(255, 255, 255));
        btn_assign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/assign.png"))); // NOI18N
        btn_assign.setText("Assign To Me");
        btn_assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_assignActionPerformed(evt);
            }
        });
        panel_assign.add(btn_assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        jPanel5.add(panel_assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 381, -1, 43));

        panel_undermedication.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_undermedication.setBackground(new java.awt.Color(102, 102, 102));
        btn_undermedication.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_undermedication.setForeground(new java.awt.Color(255, 255, 255));
        btn_undermedication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/medicalcheck.png"))); // NOI18N
        btn_undermedication.setText("Provide Medication");
        btn_undermedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_undermedicationActionPerformed(evt);
            }
        });
        panel_undermedication.add(btn_undermedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 200, 40));

        jPanel5.add(panel_undermedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 205, -1));

        lbl_txt.setBackground(new java.awt.Color(153, 153, 0));
        lbl_txt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/medication.jpg"))); // NOI18N
        jPanel5.add(lbl_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1170, 340));

        lbl_txt1.setBackground(new java.awt.Color(153, 153, 0));
        lbl_txt1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_txt1.setText("MANAGE REQUESTS");
        jPanel5.add(lbl_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_mediactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mediactionMouseClicked
        // TODO add your handling code here:
        tbl_mediaction.addMouseListener(new MouseAdapter() {

            public void mousePressed(MouseEvent e) {
                int selectedRow = tbl_mediaction.getSelectedRow();
                checkStatus(selectedRow);
            }

        });
    }//GEN-LAST:event_tbl_mediactionMouseClicked

    private void tbl_mediactionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_mediactionPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_mediactionPropertyChange

    private void btn_assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_assignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_mediaction.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a work request");
            return;
        }

        Object receiverval = tbl_mediaction.getValueAt(selectedRow, 3);
        Object statusval = tbl_mediaction.getValueAt(selectedRow, 4);
        Child childval = (Child) tbl_mediaction.getValueAt(selectedRow,5);

        if ("Request for medication".equals(statusval) || receiverval == null) {
            PharmacyWorkRequest pwr = (PharmacyWorkRequest) tbl_mediaction.getValueAt(selectedRow, 6);
            pwr.setReceiver(account);
            pwr.setStatus("Under Medication");
            pwr.setChild(childval);
            pwr.setMessage("Under Medication");

            populateTable();
            JOptionPane.showMessageDialog(null, "Work request is now assigned to you");
            checkStatus(selectedRow);
            populateTable();

        }
        else{
            if (receiverval.equals(account)) {
                JOptionPane.showMessageDialog(null, "Work request is already assigned to you");
            }
            else if (!receiverval.equals(account.getUsername())) {
                JOptionPane.showMessageDialog(null, "Work request is assigned to someone else");
                checkStatus(selectedRow);
            }
        }
    }//GEN-LAST:event_btn_assignActionPerformed

    private void btn_undermedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_undermedicationActionPerformed
        // TODO add your handling code here:
        
       
        
        //CONVERT LOCAL DATE TO DATE
        LocalDateTime now = LocalDateTime.now();
        ZoneId defaultzoneid = ZoneId.systemDefault();
        ZonedDateTime zdt = now.atZone(defaultzoneid);
        Date to_Date_now = Date.from(zdt.toInstant());
        
        DefaultTableModel model = (DefaultTableModel) tbl_mediaction.getModel();
        int selectedRow = tbl_mediaction.getSelectedRow();
        Child childval = (Child)tbl_mediaction.getValueAt(selectedRow, 5);
        
        PharmacyWorkRequest workRequest = (PharmacyWorkRequest)tbl_mediaction.getValueAt(selectedRow, 6);
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a child from table before proceeding");
            return;
        }
        else{
           
        WorkRequest wrk = (WorkRequest) tbl_mediaction.getValueAt(selectedRow,6);
        for(Child c:business.getChildDirectory().getChildlist()){
            if(childval.equals(c)){
                ChildPrescriptions cp = childval.addChildPrescriptions();
                cp.setPrescription(workRequest.getPrescription());
                cp.setPrescriptiondate(to_Date_now);
                cp.setIsMedicated(true);
                childval.setIsMediacted(true);
            }
        }
        
        for(Child c:childval.getOrg().getChildDirectory().getChildlist()){
            if(childval.equals(c)){
                ChildPrescriptions cp = childval.addChildPrescriptions();
                cp.setPrescription(workRequest.getPrescription());
                cp.setPrescriptiondate(to_Date_now);
                cp.setIsMedicated(true);
                childval.setIsMediacted(true);
            }
        }
        
        
        wrk.setStatus("Medication Provided");
        wrk.setMessage("Medication Provided");

        for(WorkRequest wr:((WorkRequest)workRequest).getSender().getWorkQueue().getWorkRequestList()){
            wr.setStatus("Medication Provided");
            wr.setMessage("Medication Provided");
        }
        
        JOptionPane.showMessageDialog(rightpanel1, "Medication Provided");
        }
        populateTable();

    }//GEN-LAST:event_btn_undermedicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_assign;
    private javax.swing.JButton btn_undermedication;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_txt;
    private javax.swing.JLabel lbl_txt1;
    private javax.swing.JPanel panel_assign;
    private javax.swing.JPanel panel_undermedication;
    private javax.swing.JTable tbl_mediaction;
    // End of variables declaration//GEN-END:variables
}
