/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RegisterParent;

import Business.Child.ChildDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Parent.Parent;
import Business.Parent.ParentDirectory;
import Business.Role.ParentRole;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import Business.Utils.ValidationHelper;
import java.awt.event.HierarchyEvent;
import userinterface.Admin.ManageCredentials;

/**
 *
 * @author jaspr
 */
public class RegisterParentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterParentJPanel
     */
    JPanel mainWorkArea;
    EcoSystem system;
    //ParentDirectory parentdirectory;
    UserAccountDirectory useraccountdir;
    
    private boolean validphone_firstparent;
    private boolean validphone_secondparent;
    private boolean validemail_firstparent;
    private boolean validemail_secondparent;
    private boolean validusername;
    private boolean validpassword;
   
    
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public RegisterParentJPanel(JPanel mainWorkArea,EcoSystem system) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.system = system;
        
        useraccountdir = system.getUserAccountDirectory();
        //parentdirectory = system.getParentDirectory();
        cardlayoutpanel.remove(this);
        CardlayoutJpanel cardlayout = new CardlayoutJpanel();
        cardlayoutpanel.add(cardlayout);
        CardLayout layout = (CardLayout) cardlayoutpanel.getLayout();
        layout.next(cardlayoutpanel);
        
        
        tick_email_firstparent.setVisible(false);
        tick_email_secondparent.setVisible(false);
        tick_firstparent.setVisible(false);
        tick_password.setVisible(false);
        tick_secondparent.setVisible(false);
        tick_username.setVisible(false);
        cancel_email_firstparent.setVisible(false);
        cancel_email_secondparent.setVisible(false);
        cancel_phone_firstparent.setVisible(false);
        cancel_phone_secondparent.setVisible(false);
        error_username.setVisible(false);
        error_password.setVisible(false);
        
    }
    
    private void checkSecondParent(){
        if(combo_status.getSelectedIndex() == 0 || combo_status.getSelectedIndex() == 1){
            //panel_secondparent.setVisible(false);
            
            cardlayoutpanel.remove(this);
            CardlayoutJpanel cardlayout = new CardlayoutJpanel();
            cardlayoutpanel.add(cardlayout);
            CardLayout layout = (CardLayout) cardlayoutpanel.getLayout();
            layout.next(cardlayoutpanel);
            //panel_extra.setVisible(true);
        }
        else if(combo_status.getSelectedIndex() == 2){
            cardlayoutpanel.remove(this);
            cardlayoutpanel.add(panel_secondparent);
            CardLayout layout = (CardLayout) cardlayoutpanel.getLayout();
            layout.next(cardlayoutpanel);
            //panel_extra.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        panel_singleparent = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        combo_gender = new javax.swing.JComboBox<>();
        txt_firstname = new javax.swing.JTextField();
        tick_email_firstparent = new javax.swing.JLabel();
        cancel_email_firstparent = new javax.swing.JLabel();
        tick_firstparent = new javax.swing.JLabel();
        cancel_phone_firstparent = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txt_income = new javax.swing.JTextField();
        txt_occupation = new javax.swing.JTextField();
        combo_religion = new javax.swing.JComboBox<>();
        combo_race = new javax.swing.JComboBox<>();
        combo_status = new javax.swing.JComboBox<>();
        jLabel60 = new javax.swing.JLabel();
        cardlayoutpanel = new javax.swing.JPanel();
        panel_secondparent = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_email_s = new javax.swing.JTextField();
        txt_lastname_s = new javax.swing.JTextField();
        txt_phone_s = new javax.swing.JTextField();
        combo_gender_s = new javax.swing.JComboBox<>();
        txt_firstname_s = new javax.swing.JTextField();
        tick_email_secondparent = new javax.swing.JLabel();
        cancel_email_secondparent = new javax.swing.JLabel();
        tick_secondparent = new javax.swing.JLabel();
        cancel_phone_secondparent = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_marital_status = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        combo_race_s = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        combo_religion_s = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txt_occupation_s = new javax.swing.JTextField();
        txt_income_s = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        combo_child_gender = new javax.swing.JComboBox<>();
        combo_child_age = new javax.swing.JComboBox<>();
        combo_child_race = new javax.swing.JComboBox<>();
        combo_child_religion = new javax.swing.JComboBox<>();
        combo_child_health = new javax.swing.JComboBox<>();
        combo_child_handicap = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        txt_state = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        radio_yes = new javax.swing.JRadioButton();
        radio_no = new javax.swing.JRadioButton();
        combo_members = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        pwdField = new javax.swing.JPasswordField();
        btn_createaccout = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        error_username = new javax.swing.JLabel();
        tick_password = new javax.swing.JLabel();
        tick_username = new javax.swing.JLabel();
        error_password = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        combo_primary_language1 = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();
        combo_psecondary_language1 = new javax.swing.JComboBox<>();
        panel_extra = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        jLabel28.setBackground(new java.awt.Color(153, 153, 0));
        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("PERSONAL INFORMATION HERE");

        panel_singleparent.setBackground(new java.awt.Color(204, 255, 153));
        panel_singleparent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setText("Gender");
        panel_singleparent.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setText("Phone");
        panel_singleparent.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setText("Email");
        panel_singleparent.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setText("Last Name");
        panel_singleparent.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setText("First Name");
        panel_singleparent.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setText("Parent Details");
        panel_singleparent.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 11, -1, -1));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        panel_singleparent.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, -1));
        panel_singleparent.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 150, -1));

        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });
        txt_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_phoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneKeyTyped(evt);
            }
        });
        panel_singleparent.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, -1));

        combo_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Female", "Male" }));
        combo_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_genderActionPerformed(evt);
            }
        });
        panel_singleparent.add(combo_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, -1));
        panel_singleparent.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 150, -1));

        tick_email_firstparent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png"))); // NOI18N
        panel_singleparent.add(tick_email_firstparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, 30));

        cancel_email_firstparent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/cancel.png"))); // NOI18N
        panel_singleparent.add(cancel_email_firstparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 180, -1, -1));

        tick_firstparent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png"))); // NOI18N
        panel_singleparent.add(tick_firstparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 30, 30));

        cancel_phone_firstparent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/cancel.png"))); // NOI18N
        panel_singleparent.add(cancel_phone_firstparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 134, -1, 30));

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setText("Relationship");
        panel_singleparent.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setText("Race");
        panel_singleparent.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("Religion");
        panel_singleparent.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setText("Occupation");
        panel_singleparent.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 76, -1));
        panel_singleparent.add(txt_income, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 120, -1));
        panel_singleparent.add(txt_occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 140, -1));

        combo_religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Religion", "Hinduism", "Buddhism", "Catholism", "Christian", "Jewish" }));
        panel_singleparent.add(combo_religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, -1));

        combo_race.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Race", "Black", "Asian", "White", "Pacific Islander" }));
        panel_singleparent.add(combo_race, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 140, -1));

        combo_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Status", "Single", "Married" }));
        combo_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_statusActionPerformed(evt);
            }
        });
        panel_singleparent.add(combo_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 140, -1));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel60.setText("Annual Income");
        panel_singleparent.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 24));

        cardlayoutpanel.setLayout(new java.awt.CardLayout());

        panel_secondparent.setBackground(new java.awt.Color(204, 255, 153));
        panel_secondparent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Gender");
        panel_secondparent.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Phone");
        panel_secondparent.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Email");
        panel_secondparent.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Last Name");
        panel_secondparent.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("First Name");
        panel_secondparent.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("SECOND PARENT");
        panel_secondparent.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 11, -1, -1));

        txt_email_s.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_email_sKeyTyped(evt);
            }
        });
        panel_secondparent.add(txt_email_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 187, 150, -1));
        panel_secondparent.add(txt_lastname_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 105, 150, -1));

        txt_phone_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phone_sActionPerformed(evt);
            }
        });
        txt_phone_s.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phone_sKeyTyped(evt);
            }
        });
        panel_secondparent.add(txt_phone_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 146, 150, -1));

        combo_gender_s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Female", "Male" }));
        panel_secondparent.add(combo_gender_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 228, 150, -1));
        panel_secondparent.add(txt_firstname_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 64, 150, -1));

        tick_email_secondparent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png"))); // NOI18N
        panel_secondparent.add(tick_email_secondparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 30, -1));

        cancel_email_secondparent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/cancel.png"))); // NOI18N
        panel_secondparent.add(cancel_email_secondparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 180, -1, -1));

        tick_secondparent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png"))); // NOI18N
        panel_secondparent.add(tick_secondparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 30, -1));

        cancel_phone_secondparent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/cancel.png"))); // NOI18N
        panel_secondparent.add(cancel_phone_secondparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 134, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Status");
        panel_secondparent.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 69, -1));
        panel_secondparent.add(txt_marital_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 150, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Race");
        panel_secondparent.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        combo_race_s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Race", "Black", "Asian", "White", "Pacific Islander" }));
        panel_secondparent.add(combo_race_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 140, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Religion");
        panel_secondparent.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        combo_religion_s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Religion", "Hinduism", "Buddhism", "Catholism", "Christian", "Jewish" }));
        panel_secondparent.add(combo_religion_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Occupation");
        panel_secondparent.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));
        panel_secondparent.add(txt_occupation_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 140, -1));

        txt_income_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_income_sActionPerformed(evt);
            }
        });
        panel_secondparent.add(txt_income_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 140, -1));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel58.setText("Annual Income");
        panel_secondparent.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, 24));

        cardlayoutpanel.add(panel_secondparent, "card2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panel_singleparent, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardlayoutpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardlayoutpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(panel_singleparent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));

        jLabel7.setBackground(new java.awt.Color(153, 153, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" YOUR CHILD PREFERNCES");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Age");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Gender");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Race");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Religion");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Health Acceptance");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("Handicap Acceptance");

        combo_child_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Female", "Male" }));

        combo_child_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Age", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17" }));

        combo_child_race.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Race", "No Prefernce", "Black", "Asian", "White", "Pacific Islander", " " }));

        combo_child_religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Religion", "No Prefernce", "Hinduism", "Buddhism", "Catholism", "Christian", "Jewish" }));

        combo_child_health.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "No health issue", "Mild is ok", "Willing to foster anyone" }));

        combo_child_handicap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "No handicap", "Mild is Ok", "Willing to foster handicap" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_child_health, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_child_religion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_child_race, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_child_age, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_child_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_child_handicap, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(combo_child_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(combo_child_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(combo_child_race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(combo_child_religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(combo_child_health, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combo_child_handicap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel34)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));

        jLabel39.setBackground(new java.awt.Color(153, 153, 0));
        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("ADDRESS INFORMATION");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setText("HOME ADDRESS");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setText("State");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setText("City");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setText("Pets in Home");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setText("Number of Members");

        radio_yes.setText("Yes");

        radio_no.setText("No");

        combo_members.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(radio_yes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radio_no, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(combo_members, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel39)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel39)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txt_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txt_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(radio_yes)
                    .addComponent(radio_no))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(combo_members, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setBorder(javax.swing.BorderFactory.createTitledBorder("USERNAME"));
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });
        jPanel5.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, -1));

        pwdField.setBorder(javax.swing.BorderFactory.createTitledBorder("PASSWORD"));
        pwdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwdFieldKeyTyped(evt);
            }
        });
        jPanel5.add(pwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, -1));

        btn_createaccout.setBackground(new java.awt.Color(51, 51, 51));
        btn_createaccout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_createaccout.setForeground(new java.awt.Color(255, 255, 255));
        btn_createaccout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btn_createaccout.setText("Create Account");
        btn_createaccout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createaccoutActionPerformed(evt);
            }
        });
        jPanel5.add(btn_createaccout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 30));

        jLabel48.setBackground(new java.awt.Color(153, 153, 0));
        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("CREATE ACCOUNT");
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 28, -1, -1));

        error_username.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        error_username.setForeground(new java.awt.Color(255, 51, 51));
        error_username.setText("Try Another Name");
        jPanel5.add(error_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        tick_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png"))); // NOI18N
        jPanel5.add(tick_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, 22));

        tick_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick.png"))); // NOI18N
        jPanel5.add(tick_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 26, 18));

        error_password.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        error_password.setForeground(new java.awt.Color(255, 51, 51));
        error_password.setText("Low Strength");
        jPanel5.add(error_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jPanel6.setBackground(new java.awt.Color(153, 153, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setBackground(new java.awt.Color(153, 153, 0));
        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("OTHER INFO");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setText("Primary Language");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 24));

        combo_primary_language1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Language", "English", "Chinese", "Hindi", "Spanish", "French" }));
        jPanel6.add(combo_primary_language1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 162, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel47.setText("Secondary Language");
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 24));

        combo_psecondary_language1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Language", "English", "Chinese", "Hindi", "Spanish", "French" }));
        jPanel6.add(combo_psecondary_language1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 162, -1));

        panel_extra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/childcare.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(panel_extra, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 85, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(panel_extra, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createaccoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createaccoutActionPerformed
        // TODO add your handling code here:
        
        Double income = 0.0;
        
        if(txt_firstname.getText().isEmpty() || txt_lastname.getText().isEmpty() || txt_phone.getText().isEmpty() ||
                txt_email.getText().isEmpty() || txt_occupation.getText().isEmpty() || txt_income.getText().isEmpty()
                
                || txt_address.getText().isEmpty() || txt_state.getText().isEmpty() || txt_city.getText().isEmpty()
                || txtUserName.getText().isEmpty() || pwdField.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(panel_secondparent, "Please Provide All Details");
           
        }
        
        
        else if(combo_child_age.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct prefeered child age");
        }
        else if(combo_child_gender.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct prefeered child gender");
        }
        else if(combo_child_handicap.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct your preference for handicap");
        }
        else if(combo_child_health.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct prefeered child health");
        }
        else if(combo_child_race.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct prefeered child race");
        }
        else if(combo_child_religion.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct prefeered child religion");
        }
        else if(combo_gender.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct parent gender");
        }
        else if(combo_members.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct number of pets you have");
        }
        else if(combo_primary_language1.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct your primary language");
        }
        else if(combo_psecondary_language1.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct your secondary language");
        }
        else if(combo_race.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct parent race");
        }
        else if(combo_religion.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct parent religion");
        }
        else if(combo_status.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(panel_secondparent, "Please selct relationship status");
        }
        
        try{
            income = Double.parseDouble(txt_income.getText());
            if(income < 50000){
                JOptionPane.showMessageDialog(panel_secondparent, "Income is less to adopt");
                return;
            }
        }  
        catch(Exception e){
            JOptionPane.showMessageDialog(panel_secondparent, "Enter correct income");
            return;
        }
        if(combo_status.getSelectedIndex()==2){
            if(combo_gender_s.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(panel_secondparent, "Please select parent gender");
            }
            if(combo_race_s.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(panel_secondparent, "Please select parent race");
            }
            if(combo_religion_s.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(panel_secondparent, "Please select parent religion");
            }
        }
        
        if(combo_status.getSelectedIndex() == 1){
            
        if(validemail_firstparent == true && validpassword == true && validphone_firstparent == true
               && validusername == true ){
            
            Parent parent = system.getParentDirectory().addParent();
           
            parent.setFirstname(txt_firstname.getText());
            parent.setLastname(txt_lastname.getText());
            parent.setPhone(Integer.parseInt(txt_phone.getText()));
            parent.setEmail(txt_email.getText());
            parent.setGender(String.valueOf(combo_gender.getSelectedItem()));
            parent.setRelation_status(String.valueOf(combo_status.getSelectedItem()));
            parent.setRace(String.valueOf(combo_race.getSelectedItem()));
            parent.setReligion(String.valueOf(combo_religion.getSelectedItem()));
            parent.setOccupation(txt_occupation.getText());
            parent.setIncome(income);
            
           
            
            if(combo_status.getSelectedIndex() == 1){
                parent.setS_firstname("");
                parent.setS_lastname("");
                parent.setS_phone(0);
                parent.setS_email("");
                parent.setS_gender("");
                parent.setS_relation_status("");
                parent.setS_race("");
                parent.setS_religion("");
                parent.setS_occupation("");
                parent.setS_income(0.0);
                
            }
            
            parent.setPreference_child_age(Integer.parseInt((String) combo_child_age.getSelectedItem()));
            parent.setPreference_child_gender(String.valueOf(combo_child_gender.getSelectedItem()));
            parent.setPreference_child_race(String.valueOf(combo_child_race.getSelectedItem()));
            parent.setPreference_child_religion(String.valueOf(combo_child_religion.getSelectedItem()));
            parent.setPreference_child_healthstatus(String.valueOf(combo_child_health.getSelectedItem()));
            parent.setPreference_child_handicapacceptance(String.valueOf(combo_child_handicap.getSelectedItem()));
            
            parent.setHome_address(txt_address.getText());
            parent.setCity(txt_city.getText());
            parent.setState(txt_state.getText());
            if(radio_yes.isSelected()){
                parent.setIsPet("yes");
            }
            else if(radio_yes.isSelected()){
                parent.setIsPet("no");
            }
            parent.setNumber_of_family_memebers(Integer.parseInt((String) combo_members.getSelectedItem()));
            
            parent.setUsername(txtUserName.getText());
            parent.setPassword(pwdField.getText());
            if(useraccountdir.checkIfUsernameIsUnique(txtUserName.getText())){
            
            useraccountdir.createUserAccount(txtUserName.getText(), pwdField.getText(), new ParentRole());
            system.getParentDirectory().getParentlist().add(parent);
            
            JOptionPane.showMessageDialog(panel_secondparent, "Parent Added! You can Now Login");
            //JOptionPane.showMessageDialog(panel_secondparent, parentdirectory.getParentlist());
            //JOptionPane.showMessageDialog(panel_secondparent, useraccountdir.getUserAccountList());
            }
            else{
                JOptionPane.showMessageDialog(panel_secondparent, "Parent Already Exist");
            }
        }
        
        }
        
        else if(combo_status.getSelectedIndex() == 2){
            
            Double parent2_income = 0.0;
            
            txt_marital_status.setText(String.valueOf(combo_status.getSelectedItem()));

            if(validemail_firstparent == true && validpassword == true && validphone_firstparent == true
               && validusername == true && validemail_secondparent == true && validphone_secondparent == true){
            
            try{
            income = Double.parseDouble(txt_income.getText());
            parent2_income = Double.parseDouble(txt_income_s.getText());
            if((income + parent2_income) < 50000){
                JOptionPane.showMessageDialog(panel_secondparent, "Income is less to adopt");
                return;
            }
            }  
            catch(Exception e){
                JOptionPane.showMessageDialog(panel_secondparent, "Enter correct income");
                return;
            }
                
            
                    
                
            Parent parent = system.getParentDirectory().addParent();
            //JOptionPane.showMessageDialog(panel_secondparent, parent);
            
            //check parent unique
            //if(parentdirectory.isParentUnique(parent) == true){
            parent.setFirstname(txt_firstname.getText());
            parent.setLastname(txt_lastname.getText());
            parent.setPhone(Integer.parseInt(txt_phone.getText()));
            parent.setEmail(txt_email.getText());
            parent.setGender(String.valueOf(combo_gender.getSelectedItem()));
            parent.setRelation_status(String.valueOf(combo_status.getSelectedItem()));
            parent.setRace(String.valueOf(combo_race.getSelectedItem()));
            parent.setReligion(String.valueOf(combo_religion.getSelectedItem()));
            parent.setOccupation(txt_occupation.getText());
            parent.setIncome(income);
            
            
            parent.setS_firstname(txt_firstname.getText());
            parent.setS_lastname(txt_lastname.getText());
            parent.setS_phone(Integer.parseInt(txt_phone.getText()));
            parent.setS_email(txt_email.getText());
            parent.setS_gender(String.valueOf(combo_gender.getSelectedItem()));
            parent.setS_relation_status(String.valueOf(combo_status.getSelectedItem()));
            parent.setS_race(String.valueOf(combo_race.getSelectedItem()));
            parent.setS_religion(String.valueOf(combo_religion.getSelectedItem()));
            parent.setS_occupation(txt_occupation.getText());
            parent.setS_income(parent2_income);
  
            parent.setPreference_child_age(Integer.parseInt((String) combo_child_age.getSelectedItem()));
            parent.setPreference_child_gender(String.valueOf(combo_child_gender.getSelectedItem()));
            parent.setPreference_child_race(String.valueOf(combo_child_race.getSelectedItem()));
            parent.setPreference_child_religion(String.valueOf(combo_child_religion.getSelectedItem()));
            parent.setPreference_child_healthstatus(String.valueOf(combo_child_health.getSelectedItem()));
            parent.setPreference_child_handicapacceptance(String.valueOf(combo_child_handicap.getSelectedItem()));
            
            parent.setHome_address(txt_address.getText());
            parent.setCity(txt_city.getText());
            parent.setState(txt_state.getText());
            if(radio_yes.isSelected()){
                parent.setIsPet("yes");
            }
            else if(radio_yes.isSelected()){
                parent.setIsPet("no");
            }
            parent.setNumber_of_family_memebers(Integer.parseInt((String) combo_members.getSelectedItem()));
            
            parent.setUsername(txtUserName.getText());
            parent.setPassword(pwdField.getText());
            
            if(useraccountdir.checkIfUsernameIsUnique(txtUserName.getText())){
            
            useraccountdir.createUserAccount(txtUserName.getText(), pwdField.getText(), new ParentRole());
            system.getParentDirectory().getParentlist().add(parent);
           
            JOptionPane.showMessageDialog(panel_secondparent, "Parent Added! You can Now Login");
            //JOptionPane.showMessageDialog(panel_secondparent, parentdirectory.getParentlist());
            //JOptionPane.showMessageDialog(panel_secondparent, useraccountdir.getUserAccountList());
            }
            else{
                JOptionPane.showMessageDialog(panel_secondparent, "Parent Already Exist");
            }
            }
            else{
                JOptionPane.showMessageDialog(panel_secondparent, "Parent Already Exist");
            }
                
            //}
        }

    }//GEN-LAST:event_btn_createaccoutActionPerformed

    private void combo_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_statusActionPerformed
        // TODO add your handling code here:
       checkSecondParent();
      
       
    }//GEN-LAST:event_combo_statusActionPerformed

    private void combo_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_genderActionPerformed

    private void txt_phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneKeyPressed

    private void txt_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneKeyTyped
        // TODO add your handling code here:
        
       txt_phone.getDocument().addDocumentListener(new DocumentListener() {
           @Override
           public void insertUpdate(DocumentEvent e) {
               checkValidation();
           }

           @Override
           public void removeUpdate(DocumentEvent e) {
               checkValidation();
           }

           @Override
           public void changedUpdate(DocumentEvent e) {
               checkValidation();
           }
           
           public void checkValidation(){
               if(!ValidationHelper.isValidContactNo(txt_phone.getText())){
                   cancel_phone_firstparent.setVisible(true);
                   tick_firstparent.setVisible(false);
                   validphone_firstparent = false;
               }
               else{
                   cancel_phone_firstparent.setVisible(false);
                   tick_firstparent.setVisible(true);
                   validphone_firstparent = true;
               }
           }
           
        
        });
    
        
    }//GEN-LAST:event_txt_phoneKeyTyped

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        // TODO add your handling code here:
        txt_email.getDocument().addDocumentListener(new DocumentListener() {
           @Override
           public void insertUpdate(DocumentEvent e) {
               checkValidation();
           }

           @Override
           public void removeUpdate(DocumentEvent e) {
               checkValidation();
           }

           @Override
           public void changedUpdate(DocumentEvent e) {
               checkValidation();
           }
           
           public void checkValidation(){
               if(!ValidationHelper.isValidEmailId(txt_email.getText())){
                   cancel_email_firstparent.setVisible(true);
                   tick_email_firstparent.setVisible(false);
                   validemail_firstparent = false;
               }
               else{
                   cancel_email_firstparent.setVisible(false);
                   tick_email_firstparent.setVisible(true);
                   validemail_firstparent = true;
               }
           }
           
        
        });
    
    }//GEN-LAST:event_txt_emailKeyTyped

    private void txt_phone_sKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phone_sKeyTyped
        // TODO add your handling code here:
        txt_phone_s.getDocument().addDocumentListener(new DocumentListener() {
           @Override
           public void insertUpdate(DocumentEvent e) {
               checkValidation();
           }

           @Override
           public void removeUpdate(DocumentEvent e) {
               checkValidation();
           }

           @Override
           public void changedUpdate(DocumentEvent e) {
               checkValidation();
           }
           
           public void checkValidation(){
               if(!ValidationHelper.isValidContactNo(txt_phone_s.getText())){
                   cancel_phone_secondparent.setVisible(true);
                   tick_secondparent.setVisible(false);
                   validphone_secondparent = false;
               }
               else{
                   cancel_phone_secondparent.setVisible(false);
                   tick_secondparent.setVisible(true);
                   validphone_secondparent = true;
               }
           }
           
        
        });
    }//GEN-LAST:event_txt_phone_sKeyTyped

    private void txt_email_sKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_email_sKeyTyped
        // TODO add your handling code here:
        txt_email_s.getDocument().addDocumentListener(new DocumentListener() {
           @Override
           public void insertUpdate(DocumentEvent e) {
               checkValidation();
           }

           @Override
           public void removeUpdate(DocumentEvent e) {
               checkValidation();
           }

           @Override
           public void changedUpdate(DocumentEvent e) {
               checkValidation();
           }
           
           public void checkValidation(){
               if(!ValidationHelper.isValidEmailId(txt_email_s.getText())){
                   cancel_email_secondparent.setVisible(true);
                   tick_email_secondparent.setVisible(false);
                   validemail_secondparent = false;
               }
               else{
                   cancel_email_secondparent.setVisible(false);
                   tick_email_secondparent.setVisible(true);
                   validemail_secondparent = true;
               }
           }
           
        
        });
    
    }//GEN-LAST:event_txt_email_sKeyTyped

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        // TODO add your handling code here:
        txtUserName.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                checkValidation();
            }

            public void removeUpdate(DocumentEvent e) {
                checkValidation();
            }

            public void insertUpdate(DocumentEvent e) {
                checkValidation();
            }

            public void checkValidation() {
                if (!system.checkIfUserIsUnique(txtUserName.getText())) {
                    JOptionPane.showMessageDialog(panel_secondparent, system.getUserAccountDirectory().getUserAccountList());
                    error_username.setVisible(true);
                    tick_username.setVisible(false);
                    validusername = false;
                } else {
                    //JOptionPane.showMessageDialog(panel_secondparent, system.getUserAccountDirectory().getUserAccountList());
                    error_username.setVisible(false);
                    tick_username.setVisible(true);
                    validusername = true;
                }
            }
        });
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void pwdFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFieldKeyReleased

    private void pwdFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdFieldKeyTyped
        // TODO add your handling code here:
        
       pwdField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                checkValidation();
            }

            public void removeUpdate(DocumentEvent e) {
                checkValidation();
            }

            public void insertUpdate(DocumentEvent e) {
                checkValidation();
            }

            public void checkValidation() {
                if(!ValidationHelper.isPasswordValid(pwdField.getText())){
                   error_password.setVisible(true);
                   tick_password.setVisible(false);
                   validpassword = false;
               }
               else{
                   error_password.setVisible(false);
                   tick_password.setVisible(true);
                   validpassword = true;
               }
            }
        });
        
        
    }//GEN-LAST:event_pwdFieldKeyTyped

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void txt_phone_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phone_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phone_sActionPerformed

    private void txt_income_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_income_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_income_sActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createaccout;
    private javax.swing.JLabel cancel_email_firstparent;
    private javax.swing.JLabel cancel_email_secondparent;
    private javax.swing.JLabel cancel_phone_firstparent;
    private javax.swing.JLabel cancel_phone_secondparent;
    private javax.swing.JPanel cardlayoutpanel;
    private javax.swing.JComboBox<String> combo_child_age;
    private javax.swing.JComboBox<String> combo_child_gender;
    private javax.swing.JComboBox<String> combo_child_handicap;
    private javax.swing.JComboBox<String> combo_child_health;
    private javax.swing.JComboBox<String> combo_child_race;
    private javax.swing.JComboBox<String> combo_child_religion;
    private javax.swing.JComboBox<String> combo_gender;
    private javax.swing.JComboBox<String> combo_gender_s;
    private javax.swing.JComboBox<String> combo_members;
    private javax.swing.JComboBox<String> combo_primary_language1;
    private javax.swing.JComboBox<String> combo_psecondary_language1;
    private javax.swing.JComboBox<String> combo_race;
    private javax.swing.JComboBox<String> combo_race_s;
    private javax.swing.JComboBox<String> combo_religion;
    private javax.swing.JComboBox<String> combo_religion_s;
    private javax.swing.JComboBox<String> combo_status;
    private javax.swing.JLabel error_password;
    private javax.swing.JLabel error_username;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel panel_extra;
    private javax.swing.JPanel panel_secondparent;
    private javax.swing.JPanel panel_singleparent;
    private javax.swing.JPasswordField pwdField;
    private javax.swing.JRadioButton radio_no;
    private javax.swing.JRadioButton radio_yes;
    private javax.swing.JLabel tick_email_firstparent;
    private javax.swing.JLabel tick_email_secondparent;
    private javax.swing.JLabel tick_firstparent;
    private javax.swing.JLabel tick_password;
    private javax.swing.JLabel tick_secondparent;
    private javax.swing.JLabel tick_username;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_email_s;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_firstname_s;
    private javax.swing.JTextField txt_income;
    private javax.swing.JTextField txt_income_s;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_lastname_s;
    private javax.swing.JTextField txt_marital_status;
    private javax.swing.JTextField txt_occupation;
    private javax.swing.JTextField txt_occupation_s;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_phone_s;
    private javax.swing.JTextField txt_state;
    // End of variables declaration//GEN-END:variables
}
