/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CulturalEventOrganiser;

import Business.Child.ChildDirectory;
import Business.EcoSystem;
import Business.Enterprise.CulturalEvents;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Parent.ParentDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EventRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaspr
 */
public class OrganiserMAnageRequest extends javax.swing.JPanel {

    /**
     * Creates new form OrganiserMAnageRequest
     */
    JPanel userProcessContainer;
    EcoSystem business;
    Enterprise enterprise;
    Network network;
    UserAccount account;
    Organization organization;
    ChildDirectory childdir;
    ParentDirectory parentdir;
    EnterpriseDirectory enterpriseDirectory;
    JPanel rightpanel1;
    public OrganiserMAnageRequest(JPanel userProcessContainer, UserAccount account,
            Network network, Organization organization, Enterprise enterprise, 
            EcoSystem business,ChildDirectory childdir,ParentDirectory parentdir,JPanel rightpanel1) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        this.network = network;
        this.organization = organization;
        this.childdir = childdir;
        this.parentdir = parentdir;
        this.rightpanel1 = rightpanel1;
        this.account = account;
        
        btn_requestreim.setVisible(false); 
        btn_addevent.setVisible(false);
        
        populateTable();
        
    }
    
    
    private void checkStatus(int selectedRow){
        DefaultTableModel model = (DefaultTableModel) tbl_events.getModel();
        Object statusval = tbl_events.getValueAt(selectedRow, 5);
        EventRequest wr = (EventRequest)tbl_events.getValueAt(selectedRow, 4);
    
        if(statusval.equals("EVENT APPROVED")){
           
           btn_addevent.setVisible(true);
   
           btn_requestreim.setVisible(true);
        }
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_events.getModel();
        model.setRowCount(0);
        for(WorkRequest workrequest:account.getWorkQueue().getWorkRequestList()){
            if(workrequest instanceof EventRequest){
                Object[] row = new Object[model.getColumnCount()];
                row[0] = ((EventRequest) workrequest).getEventname();
                row[1] = ((EventRequest) workrequest).getEventdate();
                row[2] = ((EventRequest) workrequest).getOrganisername();
                row[3] = ((EventRequest) workrequest).getVenue();
                row[4] = workrequest;
                row[5] = workrequest.getMessage();
                model.addRow(row);
            }
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_events = new javax.swing.JTable();
        btn_requestreim = new javax.swing.JButton();
        btn_addevent = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(204, 255, 0));

        jPanel6.setBackground(new java.awt.Color(153, 153, 0));

        tbl_events.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tbl_events.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Event Date", "Organiser", "Event Venue", "Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_events.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_eventsMouseClicked(evt);
            }
        });
        tbl_events.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_eventsPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_events);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btn_requestreim.setBackground(new java.awt.Color(51, 51, 51));
        btn_requestreim.setText("Request Reinbursemensts");
        btn_requestreim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_requestreimActionPerformed(evt);
            }
        });

        btn_addevent.setBackground(new java.awt.Color(51, 51, 51));
        btn_addevent.setText("Add Event");
        btn_addevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addeventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btn_requestreim, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btn_addevent, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_requestreim)
                    .addComponent(btn_addevent))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_eventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_eventsMouseClicked
        // TODO add your handling code here:
       tbl_events.addMouseListener(new MouseAdapter() {

            public void mousePressed(MouseEvent e) {
                int selectedRow = tbl_events.getSelectedRow();
                checkStatus(selectedRow);
            }

        });

    }//GEN-LAST:event_tbl_eventsMouseClicked

    private void tbl_eventsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_eventsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_eventsPropertyChange

    private void btn_requestreimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_requestreimActionPerformed
        // TODO add your handling code here:
        //CONVERT LOCAL DATE TO DATE
        if(tbl_events.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(rightpanel1, "Select Event");
            return;
        }
        EventRequest wrkreq = (EventRequest) tbl_events.getValueAt(tbl_events.getSelectedRow(), 4);
        RequestReinbursements rr = new RequestReinbursements
                            (userProcessContainer,business,organization,childdir,wrkreq,rightpanel1,account);

        userProcessContainer.add(rr);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btn_requestreimActionPerformed

    private void btn_addeventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addeventActionPerformed
        // TODO add your handling code here:
            int selectedrow = tbl_events.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tbl_events.getModel();
            Object statusval = tbl_events.getValueAt(selectedrow, 6);
            if(selectedrow<0){
                JOptionPane.showMessageDialog(rightpanel1, "Select Event");
                return;
            }
            EventRequest wr = (EventRequest)tbl_events.getValueAt(selectedrow, 4);
            Business.CulturalEvents.CulturalEvents ce = new Business.CulturalEvents.CulturalEvents();
            ce.setEventcategory(wr.getEventcategory());
            ce.setEventdate(wr.getEventdate());
            ce.setEventname(wr.getEventname());
            ce.setIsCulturalEventHappening(true);
            ce.setOrganisername(wr.getOrganisername());
            ce.setVenue(wr.getVenue());
            JOptionPane.showMessageDialog(rightpanel1, "Cultural Event Added");
    }//GEN-LAST:event_btn_addeventActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addevent;
    private javax.swing.JButton btn_requestreim;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_events;
    // End of variables declaration//GEN-END:variables
}
