/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.Customer.Customer;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.Item;
import Business.Restaurant.Menu;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaspr
 */
public class ManageMenu extends javax.swing.JPanel {

    /**
     * Creates new form ManageMenu
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    Restaurant restaurant;
    Item item;
    public ManageMenu(JPanel userProcessContainer,EcoSystem system, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        populateTable();
    }
    
    public void populateTable(){
       //Character size_here[];
       DefaultTableModel model = (DefaultTableModel)tbl_menu.getModel();
       model.setRowCount(0);
       for(Restaurant restaurant:system.getRestaurantDirectory().getRestrauntlist()){
            //JOptionPane.showMessageDialog(btn_modify, restaurant.getMenu().getItemlist());
            if(String.valueOf(restaurant.getName()).equals(String.valueOf(userAccount.getUsername()))){
                Object[] row = new Object[3];
                    for(Item item:restaurant.getMenu().getItemlist()){
                        //size_here = new Character[item.getSizearr().length];
                        //JOptionPane.showMessageDialog(btn_modify, item + " " + item.getSizearr());
                        row[0] = item;
                        row[1] = item.getItemprice();
                        for(int i=0;i<item.getSizearr().length;i++){
                            if(item.getSizearr().length == 1){
                                row[2] = item.getSizearr()[0];
                            }
                            else if(item.getSizearr().length == 2){
                                row[2] = item.getSizearr()[0] + "," + item.getSizearr()[1];
                            }
                            else if(item.getSizearr().length == 3){
                                row[2] = item.getSizearr()[0] + "," + item.getSizearr()[1] + "," + item.getSizearr()[2];
                            }
                        }
                        model.addRow(row);
                    }
            }
       }      
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        check_s = new javax.swing.JCheckBox();
        check_m = new javax.swing.JCheckBox();
        check_l = new javax.swing.JCheckBox();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_modify = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_menu = new javax.swing.JTable();
        btnmodificationsaved = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(204, 255, 102));

        jPanel3.setBackground(new java.awt.Color(204, 255, 102));

        jPanel2.setBackground(new java.awt.Color(204, 255, 102));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Item Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Item price");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Size");

        check_s.setText("S");

        check_m.setText("M");

        check_l.setText("L");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(check_s, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(check_m, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(check_l)
                        .addGap(39, 39, 39))
                    .addComponent(txt_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(check_s)
                    .addComponent(check_m)
                    .addComponent(check_l))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        btn_add.setBackground(new java.awt.Color(51, 51, 51));
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/user (3).png"))); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(51, 51, 51));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/cancel.png"))); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_modify.setBackground(new java.awt.Color(51, 51, 51));
        btn_modify.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_modify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/login.png"))); // NOI18N
        btn_modify.setText("MODIFY");
        btn_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("                                                         MANAGE MENU");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        tbl_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Name", "Item price", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_menu);

        btnmodificationsaved.setBackground(new java.awt.Color(51, 51, 51));
        btnmodificationsaved.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnmodificationsaved.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/user (3).png"))); // NOI18N
        btnmodificationsaved.setText("Save Modification");
        btnmodificationsaved.setEnabled(false);
        btnmodificationsaved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificationsavedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btn_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btn_delete))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnmodificationsaved, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 295, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificationsaved, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1129, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 171, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1129, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tbl_menu.getModel();
        int selectedrow = tbl_menu.getSelectedRow();
        Item item = (Item)model.getValueAt(selectedrow, 0);
        
        if(selectedrow<0){
            JOptionPane.showMessageDialog(btn_modify, "Please select Item to Delete");
        }
        else{
            for(Restaurant restaurant : system.getRestaurantDirectory().getRestrauntlist()){
                if(String.valueOf(restaurant.getName()).equals(String.valueOf(userAccount.getUsername()))){
                    restaurant.getMenu().deleteItem(item);
                    JOptionPane.showMessageDialog(btn_modify, "Item Deleted");
                    //JOptionPane.showMessageDialog(btn_modify, restaurant.getMenu().getItemlist());
                }
            }
        }
        populateTable();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyActionPerformed
        // TODO add your handling code here
        
        int selectedrow = tbl_menu.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tbl_menu.getModel();
        Item item = (Item)model.getValueAt(selectedrow, 0);
        if(selectedrow < 0){
            JOptionPane.showMessageDialog(txt_name, "Select Customer to modify");
        }
        else{
            txt_name.setText(String.valueOf(item.getItemname()));
            txt_price.setText(String.valueOf(item.getItemprice()));
            Character size[] = new Character[item.getSizearr().length];
            for(int i=0;i<item.getSizearr().length;i++){
                if(item.getSizearr()[i].equals('s')){
                    check_s.setSelected(true);
                }
                else if(item.getSizearr()[i].equals('m')){
                    check_m.setSelected(true);
                }
                else if(item.getSizearr()[i].equals('l')){
                    check_l.setSelected(true);
                }
            }
            btnmodificationsaved.setEnabled(true);
            btn_add.setEnabled(false);
        }
        
        
        
        
    }//GEN-LAST:event_btn_modifyActionPerformed

    private void btnmodificationsavedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificationsavedActionPerformed
        // TODO add your handling code here:
        
        if(btnmodificationsaved.isEnabled()){
            
            Double price = 0.0;
            ArrayList<Character> itemsize = new ArrayList<>();
            Character sizes[];
            HashMap<Character, Integer> sizemap = new HashMap<Character, Integer>();

            int counter = -1;
            int flag = 0;

            if(check_s.isSelected()){
                sizemap.put('s', 1);
            }
            else if(!check_s.isSelected()){
                sizemap.put('s',0);
            }
            if(check_m.isSelected()){
                sizemap.put('m', 1);
            }
            else if(!check_m.isSelected()){
                sizemap.put('m',0);
            }
            if(check_l.isSelected()){
                sizemap.put('l', 1);
            }
            else if(!check_l.isSelected()){
                sizemap.put('l',0);
            }
     
            int selectedrow = tbl_menu.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel)tbl_menu.getModel();
            Item item = (Item)model.getValueAt(selectedrow, 0);
            if(tbl_menu.getSelectedRow() < 0){
                JOptionPane.showMessageDialog(txt_name, "Please Select Customer");
            }
           
            item.setItemname(String.valueOf(txt_name.getText()));
            try{
                price = Double.valueOf(txt_price.getText());
               }
               catch(Exception e){
                   JOptionPane.showMessageDialog(btn_modify, "Please enter correct price");
                   return;
               }
               item.setItemprice(price);
               //size
               for (var entry : sizemap.entrySet()) {
                    if(entry.getValue() == 1){
                        counter++;
                        itemsize.add(entry.getKey());     
                    }
               
               }
               sizes = new Character[itemsize.size()];
               sizes = itemsize.toArray(sizes);
               item.setSizearr(sizes);
               JOptionPane.showMessageDialog(btn_modify, "Item Modified");
            
                txt_name.setText("");
                txt_price.setText("");
                check_l.setSelected(false);
                check_m.setSelected(false);
                check_s.setSelected(false);
                btn_add.setEnabled(true);
            }
            populateTable();
        
    }//GEN-LAST:event_btnmodificationsavedActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        String itemname = String.valueOf(txt_name.getText());
        Double price = 0.0;
        ArrayList<Character> itemsize = new ArrayList<>();
        Character sizes[];
        HashMap<Character, Integer> sizemap = new HashMap<Character, Integer>();
        
        int counter = -1;
        int flag = 0;
        
        if(check_s.isSelected()){
            sizemap.put('s', 1);
        }
        else if(!check_s.isSelected()){
            sizemap.put('s',0);
        }
        if(check_m.isSelected()){
            sizemap.put('m', 1);
        }
        else if(!check_m.isSelected()){
            sizemap.put('m',0);
        }
        if(check_l.isSelected()){
            sizemap.put('l', 1);
        }
        else if(!check_l.isSelected()){
            sizemap.put('l',0);
        }
        
        
        for(Restaurant restaurant:system.getRestaurantDirectory().getRestrauntlist()){
            
            if(String.valueOf(restaurant.getName()).equals(String.valueOf(userAccount.getUsername()))){
               
               if(txt_name.getText().isEmpty() || txt_price.getText().isEmpty()){
                   JOptionPane.showMessageDialog(btn_modify, "Please enter details");
                   return;
               }
               for(int i=0;i<restaurant.getMenu().getItemlist().size();i++){
                  if(restaurant.getMenu().getItemlist().get(i).getItemname().equals(String.valueOf(itemname))){
                      JOptionPane.showMessageDialog(btn_modify, "Item Already exist");
                      flag = 1;
                      return;
                  }
              }
              if(flag == 0){
              item = restaurant.getMenu().addItem();
              
              
               //name
               item.setItemname(itemname);
               //price
               try{
                price = Double.valueOf(txt_price.getText());
               }
               catch(Exception e){
                   JOptionPane.showMessageDialog(btn_modify, "Please enter correct price");
                   return;
               }
               item.setItemprice(price);
               //size
               for (var entry : sizemap.entrySet()) {
                    if(entry.getValue() == 1){
                        counter++;
                        itemsize.add(entry.getKey());     
                    }
               
               }
               sizes = new Character[itemsize.size()];
               sizes = itemsize.toArray(sizes);
               item.setSizearr(sizes);
               JOptionPane.showMessageDialog(btn_modify, "Item Added");
               /*for(int i=0;i<sizes.length;i++){
                   JOptionPane.showMessageDialog(btn_modify, sizes[i]);
               }*/
            }
            
            }
        
        }
        populateTable();
    }//GEN-LAST:event_btn_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_modify;
    private javax.swing.JButton btnmodificationsaved;
    private javax.swing.JCheckBox check_l;
    private javax.swing.JCheckBox check_m;
    private javax.swing.JCheckBox check_s;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_menu;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
