/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;


import Business.Child.Child;
import Business.Child.ChildDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Parent.ParentDirectory;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import userinterface.RegisterParent.RegisterParentJPanel;

/**
 *
 * @author jaspr
 */
public class MainScreen extends javax.swing.JPanel {

    /**
     * Creates new form MainScreen
     */
    JPanel mainWorkArea;
    UserAccount userAccount;
    EcoSystem system;
    Organization organization;
    Enterprise enterprise;
    Network network;
    ChildDirectory childdir;
    ParentDirectory parentdir;
    
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
   
    public MainScreen(JPanel mainWorkArea, Network network,Enterprise enterprise, Organization organization, UserAccount userAccount , EcoSystem system,ChildDirectory childdir, ParentDirectory parentdir){
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.userAccount = userAccount;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        this.network = network;
        this.childdir = childdir;
        this.parentdir = parentdir;
        //JOptionPane.showMessageDialog(menuPanel, userAccount);
        if(userAccount.getRole().toString().equals("Parent") && userAccount!=null){
            JOptionPane.showMessageDialog(menuPanel, "here1");
            initUserWorkAreaParentLogin();
        }
        else if(userAccount.getRole().toString().equals("Parent")){
            JOptionPane.showMessageDialog(menuPanel, "here2");
            initUserWorkAreaParent();
        }
        else{
            JOptionPane.showMessageDialog(menuPanel, "here3");
             initUserWorkArea();
        }
    }
    
    public MainScreen(JPanel mainWorkArea, EcoSystem system){
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.system = system;
       
         initUserWorkAreaParent();
  
    }

    public MainScreen(Network network,Enterprise enterprise, Organization organization, UserAccount userAccount , EcoSystem system,ChildDirectory childdir, ParentDirectory parentdir,JPanel mainWorkArea) {
        this.mainWorkArea = mainWorkArea;
        this.userAccount = userAccount;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        this.network = network;
        this.childdir = childdir;
        this.parentdir = parentdir;
        JOptionPane.showMessageDialog(menuPanel, userAccount);
         JOptionPane.showMessageDialog(menuPanel, enterprise);
          JOptionPane.showMessageDialog(menuPanel, organization);
           JOptionPane.showMessageDialog(menuPanel, network);
            JOptionPane.showMessageDialog(menuPanel, childdir);
        
        initUserWorkAreaParentLogin();
    }
    private void initUserWorkAreaParentLogin(){
        back.setVisible(false);
        btnLogOut.setVisible(true);
        CardLayout layout = (CardLayout) workArea.getLayout();
        workArea.add("workArea",userAccount.getRole().createWorkArea(workArea, userAccount,network, organization, enterprise, system,childdir,parentdir));
        layout.next(workArea);
    }
    
     private void initUserWorkArea() {
       back.setVisible(false);
       btnLogOut.setVisible(true);
       if(userAccount!=null){
            CardLayout layout = (CardLayout) workArea.getLayout();
            workArea.add("workArea",userAccount.getRole().createWorkArea(workArea, userAccount,network, organization, enterprise, system,childdir,parentdir));
            //JOptionPane.showMessageDialog(menuPanel, parentdir.getParentlist());
            layout.next(workArea);
        }
    }
     
     private void initUserWorkAreaParent(){
        //JOptionPane.showMessageDialog(menuPanel, system.getUserAccountDirectory().getUserAccountList());
        btnLogOut.setVisible(false);
        back.setVisible(true);
        CardLayout layout = (CardLayout) workArea.getLayout();
        RegisterParentJPanel registerparent = new RegisterParentJPanel(mainWorkArea,system);
        workArea.add(registerparent);
        layout.next(workArea);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        menuPanel = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        back = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1000, 700));

        splitPane.setDividerSize(1);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuPanel.setBackground(new java.awt.Color(204, 255, 153));

        btnLogOut.setBackground(new java.awt.Color(204, 255, 204));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(51, 51, 51));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/icons8-shutdown-30.png"))); // NOI18N
        btnLogOut.setText("LOGOUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(204, 255, 204));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(51, 51, 51));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackIcon.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogOut)
                    .addComponent(back))
                .addContainerGap(873, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(menuPanel);

        workArea.setBackground(new java.awt.Color(255, 255, 255));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        
        mainWorkArea.removeAll();
       
        dB4OUtil.storeSystem(system);
        
        mainWorkArea.remove(this);
        JPanel loginScreen = new LoginScreen(mainWorkArea, system);
        mainWorkArea.add("LoginScreen", loginScreen);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
       
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        mainWorkArea.removeAll();
        
        mainWorkArea.removeAll();
        dB4OUtil.storeSystem(system);
        
        mainWorkArea.remove(this);
        JPanel loginScreen = new LoginScreen(mainWorkArea, system);
        mainWorkArea.add("LoginScreen", loginScreen);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}


