/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Customer.Customer;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.DB4OUtil.DB4OUtil;
import javax.swing.JOptionPane;
import Business.Role.CustomerRole;
/**
 *
 * @author jaspr
 */
public class MainScreen extends javax.swing.JPanel {

    /**
     * Creates new form MainScreen
     */
    JPanel mainWorkArea;
    UserAccount userAccount;
    EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public MainScreen(JPanel mainWorkArea, UserAccount userAccount , EcoSystem system) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.userAccount = userAccount;
        this.system = system;
        //this.setSize(900, 700);
        
        initUserWorkArea();
    }
    
     private void initUserWorkArea() {
        if(userAccount!=null){
            /*if (){
                JOptionPane.showMessageDialog(menuPanel, "Customer");
               //greetings =  greetings + " " + ((Customer)userAccount).getName();
               workArea.add("workArea", userAccount.getRole().createWorkArea(workArea, (Customer)userAccount, system));
            }
            else if(system.getRestaurantDirectory().getRestrauntlist().contains(userAccount)){
               JOptionPane.showMessageDialog(menuPanel, "Rest");
               workArea.add("workArea", userAccount.getRole().createWorkArea(workArea, (Restaurant)userAccount, system));
            }
            else if(system.getCustomerDirectory().getCustomerlist().contains(userAccount)){
                 JOptionPane.showMessageDialog(menuPanel, "Del");
                 workArea.add("workArea", userAccount.getRole().createWorkArea(workArea, (DeliveryMan)userAccount, system));
            }
            else{
                JOptionPane.showMessageDialog(menuPanel, "sysadmin");
                workArea.add("workArea", userAccount.getRole().createWorkArea(workArea, userAccount, system));
                }*/
            //JOptionPane.showMessageDialog(menuPanel, userAccount.getRole());
            CardLayout layout = (CardLayout) workArea.getLayout();
            workArea.add("workArea", userAccount.getRole().createWorkArea(workArea, userAccount,system));
            layout.next(workArea);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        menuPanel = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1000, 700));

        splitPane.setDividerSize(1);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuPanel.setBackground(new java.awt.Color(204, 255, 153));

        btnLogOut.setBackground(new java.awt.Color(204, 255, 204));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(51, 51, 51));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons1/icons8-shutdown-30.png"))); // NOI18N
        btnLogOut.setText("LOGOUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(841, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        splitPane.setTopComponent(menuPanel);

        workArea.setBackground(new java.awt.Color(255, 255, 255));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        //mainWorkArea.removeAll();
        
        mainWorkArea.removeAll();
        dB4OUtil.storeSystem(system);
        mainWorkArea.remove(this);
        JPanel loginScreen = new LoginScreen(mainWorkArea, system);
        mainWorkArea.add("LoginScreen", loginScreen);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
       
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}


