/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BackgroundCheckManager;

import Business.Organization.Organization;
import Business.Parent.Parent;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BackgroundCheckWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.FosterAdmin.ListOfChildrenJPanel;

/**
 *
 * @author jaspr
 */
public class BackgroundCheckScheduleAppointment extends javax.swing.JPanel {

    /**
     * Creates new form BackgroundCheckScheduleAppointment
     */
    JPanel userProcessContainer;
    Organization organization;
    UserAccount account;
    Parent parent;
    JPanel rightpanel1;
    
    BackgroundCheckWorkRequest workrequest;
    
    public BackgroundCheckScheduleAppointment(JPanel userProcessContainer,
                           Organization organization,UserAccount account,
                           Parent parent,JPanel rightpanel1,BackgroundCheckWorkRequest workrequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account = account;
        this.parent = parent;
        this.rightpanel1 = rightpanel1;
        this.workrequest = workrequest;
        //JOptionPane.showMessageDialog(panel_request, parent);
        JOptionPane.showMessageDialog(panel_request, workrequest);
        
        txt_address.setText(parent.getHome_address());
        txt_name.setText(parent.getFirstname());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        date_schedule = new com.toedter.calendar.JDateChooser();
        panel_request = new javax.swing.JPanel();
        btn_schedule = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 255, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Parent Address");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 157, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Parent Name");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 157, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Schedule Appointment");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 42));
        jPanel6.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 127, -1));
        jPanel6.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 127, -1));
        jPanel6.add(date_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 252, 42));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 530, 300));

        panel_request.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_schedule.setBackground(new java.awt.Color(51, 51, 51));
        btn_schedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/appointment.png"))); // NOI18N
        btn_schedule.setText("Schedule Appointment");
        btn_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_scheduleActionPerformed(evt);
            }
        });
        panel_request.add(btn_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        jPanel5.add(panel_request, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 439, 250, 50));

        back1.setBackground(new java.awt.Color(204, 255, 0));
        back1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back1.setForeground(new java.awt.Color(51, 51, 51));
        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackIcon.png"))); // NOI18N
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel5.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, 30, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/scheduleappintment.jpg"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 420));

        jLabel5.setBackground(new java.awt.Color(153, 153, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("SCHEDULE APPOINTMENT");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_scheduleActionPerformed
        // TODO add your handling code here:
        
        //CONVERT LOCAL DATE TO DATE
        LocalDateTime now = LocalDateTime.now();
        ZoneId defaultzoneid = ZoneId.systemDefault();
        ZonedDateTime zdt = now.atZone(defaultzoneid);
        Date to_Date_now = Date.from(zdt.toInstant());
        
        String address = txt_address.getText();
        String name = txt_address.getText();
        
       
        Date scheduleddate = date_schedule.getDate();
        
        if(txt_address.getText().isEmpty()||txt_name.getText().isEmpty()
                || date_schedule.getDate()==null){
            JOptionPane.showMessageDialog(panel_request, "Please provide all Details");
        }
        else if(scheduleddate.before(to_Date_now)){
            JOptionPane.showMessageDialog(panel_request,"Please select correct issue date");
        }
        else{ 
            workrequest.setScheduleAppointment(scheduleddate);
            workrequest.setStatus("Appointment Scheduled");
            JOptionPane.showMessageDialog(panel_request, "Appointment Scheduled");
            
            for(WorkRequest wr:parent.getWorkQueue().getWorkRequestList()){
                wr.setStatus("Appointment Scheduled");
            }
            
        }

    }//GEN-LAST:event_btn_scheduleActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        //userProcessContainer.remove(this);
        //Component[] componentArray = rightpanel1.getComponents();
        //Component component = componentArray[componentArray.length - 1];
        //WorkRequestBackgroundCheck workrequestbckgroundcheck = (WorkRequestBackgroundCheck) component;
        //workrequestbckgroundcheck.populateTable();
        //workrequestbckgroundcheck.hidescheduleappointtment();
        //CardLayout layout = (CardLayout) rightpanel1.getLayout();
        //layout.previous(rightpanel1);
        //userProcessContainer.remove(this);
        //CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        //layout.previous(userProcessContainer);
        
        userProcessContainer.remove(this);
        Component[] componentArray = rightpanel1.getComponents();
        Component component = componentArray[componentArray.length - 1];
        WorkRequestBackgroundCheck listofchildren = (WorkRequestBackgroundCheck) component;
        listofchildren.populateTable();
        listofchildren.hide();
        CardLayout layout = (CardLayout) rightpanel1.getLayout();
        layout = (CardLayout) rightpanel1.getLayout();
        layout.previous(rightpanel1);
    }//GEN-LAST:event_back1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back1;
    private javax.swing.JButton btn_schedule;
    private com.toedter.calendar.JDateChooser date_schedule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panel_request;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
