/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Parent;

import Business.Child.Child;
import Business.Child.ChildDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Parent.Parent;
import Business.Parent.ParentDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BackgroundCheckWorkRequest;
import Business.WorkQueue.ParentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.FosterAdmin.ListOfChildrenJPanel;

/**
 *
 * @author jaspr
 */
public class ParentCheckStatus extends javax.swing.JPanel {

    /**
     * Creates new form ParentCheckStatus
     */
    EcoSystem system;
    JPanel userProcessContainer;
    ChildDirectory childDirectory;
    UserAccount account;
   
    JPanel rightpanel1;    
    ParentWorkRequest parentwokrequest;
    ParentDirectory parentdir;
    BackgroundCheckWorkRequest backgroundCheckWorkRequest;
    
    
    Parent parent;
    public ParentCheckStatus(EcoSystem system, JPanel userProcessContainer, 
                                ChildDirectory childDirectory,UserAccount account, 
                                JPanel rightpanel,ParentDirectory parentdir,Parent parent) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.childDirectory = childDirectory;
        this.account = account;
        rightpanel1 = rightpanel;
        this.parentdir = parentdir;
        this.parent = parent;
        
        lbl.setVisible(false);
        panel_viewappoitment.setVisible(false);
        btn_viewAppointment.setVisible(false);
       
       
        JOptionPane.showMessageDialog(rightpanel, parent.getWorkQueue().getWorkRequestList());
        
        populateTable();
    }
    
    public void checkStatus(int selectedRow){
        DefaultTableModel model = (DefaultTableModel) tbl_parentcheckstatus.getModel();
        Object statusval = tbl_parentcheckstatus.getValueAt(selectedRow, 1);
        
        if(statusval.equals("Appointment Scheduled")){
            panel_viewappoitment.setVisible(true);
            btn_viewAppointment.setVisible(true);
            
        }
        else if(statusval.equals("ADOPTED")){
            parent.setFlag(false);
            panel_viewappoitment.setVisible(false);
            btn_viewAppointment.setVisible(false);           
        }
      
        else{          
            panel_viewappoitment.setVisible(false);
            btn_viewAppointment.setVisible(false);
        }
        
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tbl_parentcheckstatus.getModel();
        model.setRowCount(0);
        
        for(WorkRequest workrequest:parent.getWorkQueue().getWorkRequestList()){
            if(workrequest instanceof ParentWorkRequest){
               
                    Object[] row = new Object[2];
                    row[0] = ((ParentWorkRequest) workrequest).getChild();
                    if(workrequest.getStatus().equals("APPROVED TO ADOPT")){
                        row[1] = "ADOPTED";
                    }
                    else{
                    row[1] =  workrequest.getStatus();
                    }
                    model.addRow(row);
            }

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_parentcheckstatus = new javax.swing.JTable();
        panel_viewappoitment = new javax.swing.JPanel();
        btn_viewAppointment = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(204, 255, 0));

        jPanel6.setBackground(new java.awt.Color(153, 153, 0));

        tbl_parentcheckstatus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tbl_parentcheckstatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Child To Adopt", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_parentcheckstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_parentcheckstatusMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_parentcheckstatus);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_viewAppointment.setBackground(new java.awt.Color(51, 51, 51));
        btn_viewAppointment.setText("View Appointment Details");
        btn_viewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewAppointmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_viewappoitmentLayout = new javax.swing.GroupLayout(panel_viewappoitment);
        panel_viewappoitment.setLayout(panel_viewappoitmentLayout);
        panel_viewappoitmentLayout.setHorizontalGroup(
            panel_viewappoitmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_viewappoitmentLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btn_viewAppointment)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panel_viewappoitmentLayout.setVerticalGroup(
            panel_viewappoitmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_viewappoitmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_viewAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lbl.setText("jLabel1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(panel_viewappoitment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_viewappoitment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(307, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1273, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewAppointmentActionPerformed
        // TODO add your handling code here:
        for(WorkRequest workrequest:system.getWorkQueue().getWorkRequestList()){
            if(workrequest instanceof BackgroundCheckWorkRequest){
                if(((BackgroundCheckWorkRequest) workrequest).getScheduleAppointment()!=null){
                    lbl.setText("Appointment on"+" "+((BackgroundCheckWorkRequest) workrequest).getScheduleAppointment()+" " +"at your place");
                    lbl.setVisible(true);
                }
            }
        }
      
    }//GEN-LAST:event_btn_viewAppointmentActionPerformed

    private void tbl_parentcheckstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_parentcheckstatusMouseClicked
        // TODO add your handling code here:
        tbl_parentcheckstatus.addMouseListener(new MouseAdapter() {
           
            public void mousePressed(MouseEvent e) {
              int selectedRow = tbl_parentcheckstatus.getSelectedRow();
              checkStatus(selectedRow);
            }
           
       });
    }//GEN-LAST:event_tbl_parentcheckstatusMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_viewAppointment;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl;
    private javax.swing.JPanel panel_viewappoitment;
    private javax.swing.JTable tbl_parentcheckstatus;
    // End of variables declaration//GEN-END:variables
}
